import type { MedicalFieldConfig } from "./medicalFieldConfig";

export const otherMedicalFieldConfig: MedicalFieldConfig[] = [
  { row: 2, id: "other_medical_2", testCode: "2DE", section: "2D ECHO", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 3, id: "other_medical_3", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 4, id: "other_medical_4", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 5, id: "other_medical_5", testCode: "2DE", section: "2D ECHO", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 6, id: "other_medical_6", testCode: "2DE", section: "2D ECHO", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 7, id: "other_medical_7", testCode: "2DE", section: "2D ECHO", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 8, id: "other_medical_8", testCode: "2DE", section: "2D ECHO", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 9, id: "other_medical_9", testCode: "2DE", section: "2D ECHO", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 10, id: "other_medical_10", testCode: "2DE", section: "2D ECHO", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 11, id: "other_medical_11", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 12, id: "other_medical_12", testCode: "", section: "", type: "", field: "3. Mild Changes", dataType: "", options: "", mandatory: "" },
  { row: 13, id: "other_medical_13", testCode: "", section: "", type: "", field: "4. Moderate Changes", dataType: "", options: "", mandatory: "" },
  { row: 14, id: "other_medical_14", testCode: "", section: "", type: "", field: "5. Normal", dataType: "", options: "", mandatory: "" },
  { row: 15, id: "other_medical_15", testCode: "", section: "", type: "", field: "6. Severe Changes", dataType: "", options: "", mandatory: "" },
  { row: 16, id: "other_medical_16", testCode: "2DE", section: "2D ECHO", type: "Ejaction Fraction", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 17, id: "other_medical_17", testCode: "2DE", section: "2D ECHO", type: "Ejaction Result", field: "As per \"Ejaction Fraction\" showing below option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 18, id: "other_medical_18", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 19, id: "other_medical_19", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 20, id: "other_medical_20", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 21, id: "other_medical_21", testCode: "2DE", section: "2D ECHO", type: "Rejection Abnormality", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 22, id: "other_medical_22", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 23, id: "other_medical_23", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 24, id: "other_medical_24", testCode: "2DE", section: "2D ECHO", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 25, id: "other_medical_25", testCode: "BUN", section: "Blood Urea and Nitro", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 26, id: "other_medical_26", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 27, id: "other_medical_27", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 28, id: "other_medical_28", testCode: "BUN", section: "Blood Urea and Nitro", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 29, id: "other_medical_29", testCode: "BUN", section: "Blood Urea and Nitro", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 30, id: "other_medical_30", testCode: "BUN", section: "Blood Urea and Nitro", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 31, id: "other_medical_31", testCode: "BUN", section: "Blood Urea and Nitro", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 32, id: "other_medical_32", testCode: "BUN", section: "Blood Urea and Nitro", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 33, id: "other_medical_33", testCode: "BUN", section: "Blood Urea and Nitro", type: "Findings", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 34, id: "other_medical_34", testCode: "BUN", section: "Blood Urea and Nitro", type: "Result", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 35, id: "other_medical_35", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 36, id: "other_medical_36", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 37, id: "other_medical_37", testCode: "BUN", section: "Blood Urea and Nitro", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 38, id: "other_medical_38", testCode: "CXR", section: "CXR", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 39, id: "other_medical_39", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 40, id: "other_medical_40", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 41, id: "other_medical_41", testCode: "CXR", section: "CXR", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 42, id: "other_medical_42", testCode: "CXR", section: "CXR", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 43, id: "other_medical_43", testCode: "CXR", section: "CXR", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 44, id: "other_medical_44", testCode: "CXR", section: "CXR", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 45, id: "other_medical_45", testCode: "CXR", section: "CXR", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 46, id: "other_medical_46", testCode: "CXR", section: "CXR", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 47, id: "other_medical_47", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 48, id: "other_medical_48", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 49, id: "other_medical_49", testCode: "CXR", section: "CXR", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 50, id: "other_medical_50", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 51, id: "other_medical_51", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 52, id: "other_medical_52", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 53, id: "other_medical_53", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 54, id: "other_medical_54", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 55, id: "other_medical_55", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 56, id: "other_medical_56", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 57, id: "other_medical_57", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 58, id: "other_medical_58", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 59, id: "other_medical_59", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 60, id: "other_medical_60", testCode: "", section: "", type: "", field: "3. Mild Changes", dataType: "", options: "", mandatory: "" },
  { row: 61, id: "other_medical_61", testCode: "", section: "", type: "", field: "4. Moderate Changes", dataType: "", options: "", mandatory: "" },
  { row: 62, id: "other_medical_62", testCode: "", section: "", type: "", field: "5. Normal", dataType: "", options: "", mandatory: "" },
  { row: 63, id: "other_medical_63", testCode: "", section: "", type: "", field: "6. Severe Changes", dataType: "", options: "", mandatory: "" },
  { row: 64, id: "other_medical_64", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Ejaction Fraction", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 65, id: "other_medical_65", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Ejaction Result", field: "As per \"Ejaction Fraction\" showing below option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 66, id: "other_medical_66", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 67, id: "other_medical_67", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 68, id: "other_medical_68", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 69, id: "other_medical_69", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Rejection Abnormality", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 70, id: "other_medical_70", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 71, id: "other_medical_71", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 72, id: "other_medical_72", testCode: "DSE", section: "DOBUTAMINE STRESS ECHOCARDIOGRAM", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 73, id: "other_medical_73", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 74, id: "other_medical_74", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 75, id: "other_medical_75", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 76, id: "other_medical_76", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 77, id: "other_medical_77", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 78, id: "other_medical_78", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 79, id: "other_medical_79", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 80, id: "other_medical_80", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 81, id: "other_medical_81", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 82, id: "other_medical_82", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 83, id: "other_medical_83", testCode: "", section: "", type: "", field: "3. Mild Changes", dataType: "", options: "", mandatory: "" },
  { row: 84, id: "other_medical_84", testCode: "", section: "", type: "", field: "4. Moderate Changes", dataType: "", options: "", mandatory: "" },
  { row: 85, id: "other_medical_85", testCode: "", section: "", type: "", field: "5. Normal", dataType: "", options: "", mandatory: "" },
  { row: 86, id: "other_medical_86", testCode: "", section: "", type: "", field: "6. Severe Changes", dataType: "", options: "", mandatory: "" },
  { row: 87, id: "other_medical_87", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Ejaction Fraction", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 88, id: "other_medical_88", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Ejaction Result", field: "As per \"Ejaction Fraction\" showing below option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 89, id: "other_medical_89", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 90, id: "other_medical_90", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 91, id: "other_medical_91", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 92, id: "other_medical_92", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Rejection Abnormality", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 93, id: "other_medical_93", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 94, id: "other_medical_94", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 95, id: "other_medical_95", testCode: "SEO", section: "EXERCISE STRESS ECHOCARDIOGRAM", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 96, id: "other_medical_96", testCode: "ECG", section: "ECG", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 97, id: "other_medical_97", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 98, id: "other_medical_98", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 99, id: "other_medical_99", testCode: "ECG", section: "ECG", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 100, id: "other_medical_100", testCode: "ECG", section: "ECG", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 101, id: "other_medical_101", testCode: "ECG", section: "ECG", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 102, id: "other_medical_102", testCode: "ECG", section: "ECG", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 103, id: "other_medical_103", testCode: "ECG", section: "ECG", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 104, id: "other_medical_104", testCode: "ECG", section: "ECG", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 105, id: "other_medical_105", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 106, id: "other_medical_106", testCode: "", section: "", type: "", field: "3. Mild Changes", dataType: "", options: "", mandatory: "" },
  { row: 107, id: "other_medical_107", testCode: "", section: "", type: "", field: "4. Moderate Changes", dataType: "", options: "", mandatory: "" },
  { row: 108, id: "other_medical_108", testCode: "", section: "", type: "", field: "5. Normal", dataType: "", options: "", mandatory: "" },
  { row: 109, id: "other_medical_109", testCode: "", section: "", type: "", field: "6. Severe Changes", dataType: "", options: "", mandatory: "" },
  { row: 110, id: "other_medical_110", testCode: "ECG", section: "ECG", type: "Axis", field: "1.--Select--", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 111, id: "other_medical_111", testCode: "", section: "", type: "", field: "2. Interminate", dataType: "", options: "", mandatory: "" },
  { row: 112, id: "other_medical_112", testCode: "", section: "", type: "", field: "3. LAD", dataType: "", options: "", mandatory: "" },
  { row: 113, id: "other_medical_113", testCode: "", section: "", type: "", field: "4. LAHB", dataType: "", options: "", mandatory: "" },
  { row: 114, id: "other_medical_114", testCode: "", section: "", type: "", field: "5. Normal", dataType: "", options: "", mandatory: "" },
  { row: 115, id: "other_medical_115", testCode: "", section: "", type: "", field: "6. RAD", dataType: "", options: "", mandatory: "" },
  { row: 116, id: "other_medical_116", testCode: "ECG", section: "ECG", type: "Heart Rate", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 117, id: "other_medical_117", testCode: "ECG", section: "ECG", type: "Heart Rating Finding", field: "As Per heart rate Display Below Option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 118, id: "other_medical_118", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 119, id: "other_medical_119", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 120, id: "other_medical_120", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 121, id: "other_medical_121", testCode: "ECG", section: "ECG", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 122, id: "other_medical_122", testCode: "MAM", section: "MAMMOGRAM", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 123, id: "other_medical_123", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 124, id: "other_medical_124", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 125, id: "other_medical_125", testCode: "MAM", section: "MAMMOGRAM", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 126, id: "other_medical_126", testCode: "MAM", section: "MAMMOGRAM", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 127, id: "other_medical_127", testCode: "MAM", section: "MAMMOGRAM", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 128, id: "other_medical_128", testCode: "MAM", section: "MAMMOGRAM", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 129, id: "other_medical_129", testCode: "MAM", section: "MAMMOGRAM", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 130, id: "other_medical_130", testCode: "MAM", section: "MAMMOGRAM", type: "Result", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 131, id: "other_medical_131", testCode: "", section: "", type: "", field: "2. Abnoramal", dataType: "", options: "", mandatory: "" },
  { row: 132, id: "other_medical_132", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 133, id: "other_medical_133", testCode: "MAM", section: "MAMMOGRAM", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 134, id: "other_medical_134", testCode: "UMA", section: "MICROALBUMINURIA", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 135, id: "other_medical_135", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 136, id: "other_medical_136", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 137, id: "other_medical_137", testCode: "UMA", section: "MICROALBUMINURIA", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 138, id: "other_medical_138", testCode: "UMA", section: "MICROALBUMINURIA", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 139, id: "other_medical_139", testCode: "UMA", section: "MICROALBUMINURIA", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 140, id: "other_medical_140", testCode: "UMA", section: "MICROALBUMINURIA", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 141, id: "other_medical_141", testCode: "UMA", section: "MICROALBUMINURIA", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 142, id: "other_medical_142", testCode: "UMA", section: "MICROALBUMINURIA", type: "Findings", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 143, id: "other_medical_143", testCode: "UMA", section: "MICROALBUMINURIA", type: "Result", field: "As Per Findings Values Display Below Option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 144, id: "other_medical_144", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 145, id: "other_medical_145", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 146, id: "other_medical_146", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 147, id: "other_medical_147", testCode: "UMA", section: "MICROALBUMINURIA", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 148, id: "other_medical_148", testCode: "PAP", section: "PAP SMEAR", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 149, id: "other_medical_149", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 150, id: "other_medical_150", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 151, id: "other_medical_151", testCode: "PAP", section: "PAP SMEAR", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 152, id: "other_medical_152", testCode: "PAP", section: "PAP SMEAR", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 153, id: "other_medical_153", testCode: "PAP", section: "PAP SMEAR", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 154, id: "other_medical_154", testCode: "PAP", section: "PAP SMEAR", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 155, id: "other_medical_155", testCode: "PAP", section: "PAP SMEAR", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 156, id: "other_medical_156", testCode: "PAP", section: "PAP SMEAR", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 157, id: "other_medical_157", testCode: "", section: "", type: "", field: "2. Abnoramal", dataType: "", options: "", mandatory: "" },
  { row: 158, id: "other_medical_158", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 159, id: "other_medical_159", testCode: "PAP", section: "PAP SMEAR", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 160, id: "other_medical_160", testCode: "PFT", section: "PFT", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 161, id: "other_medical_161", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 162, id: "other_medical_162", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 163, id: "other_medical_163", testCode: "PFT", section: "PFT", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 164, id: "other_medical_164", testCode: "PFT", section: "PFT", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 165, id: "other_medical_165", testCode: "PFT", section: "PFT", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 166, id: "other_medical_166", testCode: "PFT", section: "PFT", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 167, id: "other_medical_167", testCode: "PFT", section: "PFT", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 168, id: "other_medical_168", testCode: "PFT", section: "PFT", type: "Inspiration", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 169, id: "other_medical_169", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 170, id: "other_medical_170", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 171, id: "other_medical_171", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 172, id: "other_medical_172", testCode: "PFT", section: "PFT", type: "Expiration", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 173, id: "other_medical_173", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 174, id: "other_medical_174", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 175, id: "other_medical_175", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 176, id: "other_medical_176", testCode: "PFT", section: "PFT", type: "FEV1", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 177, id: "other_medical_177", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 178, id: "other_medical_178", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 179, id: "other_medical_179", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 180, id: "other_medical_180", testCode: "PFT", section: "PFT", type: "FVC", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 181, id: "other_medical_181", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 182, id: "other_medical_182", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 183, id: "other_medical_183", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 184, id: "other_medical_184", testCode: "PFT", section: "PFT", type: "FEV1/FVC", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 185, id: "other_medical_185", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 186, id: "other_medical_186", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 187, id: "other_medical_187", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 188, id: "other_medical_188", testCode: "PFT", section: "PFT", type: "RV", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 189, id: "other_medical_189", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 190, id: "other_medical_190", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 191, id: "other_medical_191", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 192, id: "other_medical_192", testCode: "PFT", section: "PFT", type: "RC", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 193, id: "other_medical_193", testCode: "PFT", section: "PFT", type: "Findings", field: "Auto Populate value basis the normal range logic", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 194, id: "other_medical_194", testCode: "", section: "", type: "", field: "System.Xml.XmlElement", dataType: "", options: "", mandatory: "" },
  { row: 195, id: "other_medical_195", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 196, id: "other_medical_196", testCode: "PSA", section: "PSA", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 197, id: "other_medical_197", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 198, id: "other_medical_198", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 199, id: "other_medical_199", testCode: "PSA", section: "PSA", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 200, id: "other_medical_200", testCode: "PSA", section: "PSA", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 201, id: "other_medical_201", testCode: "PSA", section: "PSA", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 202, id: "other_medical_202", testCode: "PSA", section: "PSA", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 203, id: "other_medical_203", testCode: "PSA", section: "PSA", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 204, id: "other_medical_204", testCode: "PSA", section: "PSA", type: "Findings", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 205, id: "other_medical_205", testCode: "PSA", section: "PSA", type: "Finding Result", field: "As Per Findings Values Display Below Option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 206, id: "other_medical_206", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 207, id: "other_medical_207", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 208, id: "other_medical_208", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 209, id: "other_medical_209", testCode: "PSA", section: "PSA", type: "Remarks", field: "User Editable", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 210, id: "other_medical_210", testCode: "", section: "STOOL TEST", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 211, id: "other_medical_211", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 212, id: "other_medical_212", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 213, id: "other_medical_213", testCode: "", section: "STOOL TEST", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 214, id: "other_medical_214", testCode: "", section: "STOOL TEST", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 215, id: "other_medical_215", testCode: "", section: "STOOL TEST", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 216, id: "other_medical_216", testCode: "", section: "STOOL TEST", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 217, id: "other_medical_217", testCode: "", section: "STOOL TEST", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 218, id: "other_medical_218", testCode: "", section: "STOOL TEST", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 219, id: "other_medical_219", testCode: "", section: "", type: "", field: "2. Abnoramal", dataType: "", options: "", mandatory: "" },
  { row: 220, id: "other_medical_220", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 221, id: "other_medical_221", testCode: "", section: "STOOL TEST", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 222, id: "other_medical_222", testCode: "TMT", section: "TMT", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 223, id: "other_medical_223", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 224, id: "other_medical_224", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 225, id: "other_medical_225", testCode: "TMT", section: "TMT", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 226, id: "other_medical_226", testCode: "TMT", section: "TMT", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 227, id: "other_medical_227", testCode: "TMT", section: "TMT", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 228, id: "other_medical_228", testCode: "TMT", section: "TMT", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 229, id: "other_medical_229", testCode: "TMT", section: "TMT", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 230, id: "other_medical_230", testCode: "TMT", section: "TMT", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 231, id: "other_medical_231", testCode: "", section: "", type: "", field: "2. Positive", dataType: "", options: "", mandatory: "" },
  { row: 232, id: "other_medical_232", testCode: "", section: "", type: "", field: "3. Mild Changes", dataType: "", options: "", mandatory: "" },
  { row: 233, id: "other_medical_233", testCode: "", section: "", type: "", field: "4. Moderate Changes", dataType: "", options: "", mandatory: "" },
  { row: 234, id: "other_medical_234", testCode: "", section: "", type: "", field: "5. Negative", dataType: "", options: "", mandatory: "" },
  { row: 235, id: "other_medical_235", testCode: "", section: "", type: "", field: "6. Severe Changes", dataType: "", options: "", mandatory: "" },
  { row: 236, id: "other_medical_236", testCode: "TMT", section: "TMT", type: "METS", field: "---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 237, id: "other_medical_237", testCode: "", section: "", type: "", field: "1 to 18 Selectable Values", dataType: "", options: "", mandatory: "" },
  { row: 238, id: "other_medical_238", testCode: "TMT", section: "TMT", type: "Heart Rating Finding", field: "Enter Values(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 239, id: "other_medical_239", testCode: "TMT", section: "TMT", type: "Heart Rate Result", field: "As Per Heart Findings Values Display Below Option", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 240, id: "other_medical_240", testCode: "", section: "", type: "", field: "", dataType: "", options: "", mandatory: "" },
  { row: 241, id: "other_medical_241", testCode: "", section: "", type: "", field: "1. Normal", dataType: "", options: "", mandatory: "" },
  { row: 242, id: "other_medical_242", testCode: "", section: "", type: "", field: "2. Abnormal", dataType: "", options: "", mandatory: "" },
  { row: 243, id: "other_medical_243", testCode: "TMT", section: "TMT", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 244, id: "other_medical_244", testCode: "USG", section: "USG", type: "Medical Type", field: "1. ---Select---", dataType: "No", options: "Yes", mandatory: "Yes" },
  { row: 245, id: "other_medical_245", testCode: "", section: "", type: "", field: "2. PAST MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 246, id: "other_medical_246", testCode: "", section: "", type: "", field: "3. REGULAR MEDICAL", dataType: "", options: "", mandatory: "" },
  { row: 247, id: "other_medical_247", testCode: "USG", section: "USG", type: "Test Date", field: "Enter Date(User Editable)", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 248, id: "other_medical_248", testCode: "USG", section: "USG", type: "Examinee Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 249, id: "other_medical_249", testCode: "USG", section: "USG", type: "Diagnostic Centre Name", field: "Free Text", dataType: "Yes", options: "Yes", mandatory: "No" },
  { row: 250, id: "other_medical_250", testCode: "USG", section: "USG", type: "Doctor Name", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 251, id: "other_medical_251", testCode: "USG", section: "USG", type: "Doctor Registration No.", field: "Free Text", dataType: "No", options: "Yes", mandatory: "No" },
  { row: 252, id: "other_medical_252", testCode: "USG", section: "USG", type: "Findings", field: "1. ---Select---", dataType: "Yes", options: "Yes", mandatory: "Yes" },
  { row: 253, id: "other_medical_253", testCode: "", section: "", type: "", field: "2. Abnoramal", dataType: "", options: "", mandatory: "" },
  { row: 254, id: "other_medical_254", testCode: "", section: "", type: "", field: "3. Normal", dataType: "", options: "", mandatory: "" },
  { row: 255, id: "other_medical_255", testCode: "USG", section: "USG", type: "Remarks", field: "User Editable", dataType: "No", options: "Yes", mandatory: "Yes" },
];
