import type { MedicalFieldConfig } from './medicalFieldConfig';

export const otherMedicalViewFieldConfig: MedicalFieldConfig[] = [
  { row: 2, id: 'other_view_2', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 3, id: 'other_view_3', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 4, id: 'other_view_4', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nMild Changes\nModerate Changes\nNormal\nSevere Changes', mandatory: 'Mandatory' },
  { row: 5, id: 'other_view_5', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Ejection Fraction', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 6, id: 'other_view_6', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Ejection Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto- populated' },
  { row: 7, id: 'other_view_7', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Rejection Abnormality', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 8, id: 'other_view_8', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 9, id: 'other_view_9', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 10, id: 'other_view_10', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 11, id: 'other_view_11', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 12, id: 'other_view_12', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 13, id: 'other_view_13', testCode: '2DECHO', section: '2DECHO', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 14, id: 'other_view_14', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 15, id: 'other_view_15', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 16, id: 'other_view_16', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Findings', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 17, id: 'other_view_17', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto- populated' },
  { row: 18, id: 'other_view_18', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 19, id: 'other_view_19', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 20, id: 'other_view_20', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 21, id: 'other_view_21', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 22, id: 'other_view_22', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 23, id: 'other_view_23', testCode: 'BLOOD_UREA_AND_NITRO', section: 'BLOOD UREA and NITRO', type: 'Main', field: 'Remark', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 24, id: 'other_view_24', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 25, id: 'other_view_25', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 26, id: 'other_view_26', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 27, id: 'other_view_27', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 28, id: 'other_view_28', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 29, id: 'other_view_29', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 30, id: 'other_view_30', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 31, id: 'other_view_31', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 32, id: 'other_view_32', testCode: 'CXR', section: 'CXR', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 33, id: 'other_view_33', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 34, id: 'other_view_34', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 35, id: 'other_view_35', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nNormal\nMild Changes\nModerate Changes\nAbnormal\nSevere Changes', mandatory: 'Mandatory' },
  { row: 36, id: 'other_view_36', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Ejection Fraction', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 37, id: 'other_view_37', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Ejection Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto- populated' },
  { row: 38, id: 'other_view_38', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Rejection Abnormality', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 39, id: 'other_view_39', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 40, id: 'other_view_40', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 41, id: 'other_view_41', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 42, id: 'other_view_42', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 43, id: 'other_view_43', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 44, id: 'other_view_44', testCode: 'DOBUTAMINE_STRESS_EC', section: 'DOBUTAMINE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Remark', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 45, id: 'other_view_45', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 46, id: 'other_view_46', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 47, id: 'other_view_47', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nNormal\nMild Changes\nModerate Changes\nAbnormal\nSevere Changes', mandatory: 'Mandatory' },
  { row: 48, id: 'other_view_48', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Ejection Fraction', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 49, id: 'other_view_49', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Ejection Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto- populated' },
  { row: 50, id: 'other_view_50', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Rejection Abnormality', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 51, id: 'other_view_51', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 52, id: 'other_view_52', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 53, id: 'other_view_53', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 54, id: 'other_view_54', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 55, id: 'other_view_55', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 56, id: 'other_view_56', testCode: 'EXERCISE_STRESS_ECHO', section: 'EXERCISE STRESS ECHOCARDIOGRAM', type: 'Main', field: 'Remark', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 57, id: 'other_view_57', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 58, id: 'other_view_58', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 59, id: 'other_view_59', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nMild Changes\nModerate Changes\nNormal\nSevere Changes', mandatory: 'Mandatory' },
  { row: 60, id: 'other_view_60', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Axis', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nIndeterminate\nLAD\nLAHB\nLPHB\nNormal\nRAD', mandatory: 'Non-Mandatory' },
  { row: 61, id: 'other_view_61', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Heart Rate', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 62, id: 'other_view_62', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Heart Rate Finding', dataType: 'Auto-populated', options: '', mandatory: 'Auto- populated' },
  { row: 63, id: 'other_view_63', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 64, id: 'other_view_64', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 65, id: 'other_view_65', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 66, id: 'other_view_66', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 67, id: 'other_view_67', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 68, id: 'other_view_68', testCode: 'ECG', section: 'ECG', type: 'Main', field: 'Remark', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 69, id: 'other_view_69', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 70, id: 'other_view_70', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 71, id: 'other_view_71', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 72, id: 'other_view_72', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 73, id: 'other_view_73', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 74, id: 'other_view_74', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 75, id: 'other_view_75', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 76, id: 'other_view_76', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 77, id: 'other_view_77', testCode: 'MAMMOGRAM', section: 'MAMMOGRAM', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 78, id: 'other_view_78', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 79, id: 'other_view_79', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 80, id: 'other_view_80', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 81, id: 'other_view_81', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 82, id: 'other_view_82', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 83, id: 'other_view_83', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 84, id: 'other_view_84', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 85, id: 'other_view_85', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 86, id: 'other_view_86', testCode: 'PAP_SMEAR', section: 'PAP SMEAR', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 87, id: 'other_view_87', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Mandatory' },
  { row: 88, id: 'other_view_88', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 89, id: 'other_view_89', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 90, id: 'other_view_90', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 91, id: 'other_view_91', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 92, id: 'other_view_92', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 93, id: 'other_view_93', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 94, id: 'other_view_94', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Inspiration', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 95, id: 'other_view_95', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'Expiration', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 96, id: 'other_view_96', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'FEV1', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 97, id: 'other_view_97', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'FVC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 98, id: 'other_view_98', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'FEV1/FVC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 99, id: 'other_view_99', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'RV', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 100, id: 'other_view_100', testCode: 'PFT', section: 'PFT', type: 'Main', field: 'VC', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 101, id: 'other_view_101', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 102, id: 'other_view_102', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 103, id: 'other_view_103', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 104, id: 'other_view_104', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 105, id: 'other_view_105', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 106, id: 'other_view_106', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 107, id: 'other_view_107', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 108, id: 'other_view_108', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 109, id: 'other_view_109', testCode: 'STOOL_TEST', section: 'STOOL TEST', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 110, id: 'other_view_110', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 111, id: 'other_view_111', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 112, id: 'other_view_112', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPositive\nMild Changes\nModerate Changes\nNegative\nSevere Changes', mandatory: 'Mandatory' },
  { row: 113, id: 'other_view_113', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'METS', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18', mandatory: 'Mandatory' },
  { row: 114, id: 'other_view_114', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Heart Rate Finding', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 115, id: 'other_view_115', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Heart Rate Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto- populated' },
  { row: 116, id: 'other_view_116', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 117, id: 'other_view_117', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 118, id: 'other_view_118', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 119, id: 'other_view_119', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 120, id: 'other_view_120', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 121, id: 'other_view_121', testCode: 'TMT', section: 'TMT', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 122, id: 'other_view_122', testCode: 'USG', section: 'USG', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL \nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 123, id: 'other_view_123', testCode: 'USG', section: 'USG', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 124, id: 'other_view_124', testCode: 'USG', section: 'USG', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 125, id: 'other_view_125', testCode: 'USG', section: 'USG', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 126, id: 'other_view_126', testCode: 'USG', section: 'USG', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 127, id: 'other_view_127', testCode: 'USG', section: 'USG', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 128, id: 'other_view_128', testCode: 'USG', section: 'USG', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 129, id: 'other_view_129', testCode: 'USG', section: 'USG', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 130, id: 'other_view_130', testCode: 'USG', section: 'USG', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 131, id: 'other_view_131', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 132, id: 'other_view_132', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 133, id: 'other_view_133', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Findings', dataType: 'Dropdown', options: 'Dropdown\n---SELECT---\nAbnormal\nNormal', mandatory: 'Mandatory' },
  { row: 134, id: 'other_view_134', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 135, id: 'other_view_135', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 136, id: 'other_view_136', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 137, id: 'other_view_137', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 138, id: 'other_view_138', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 139, id: 'other_view_139', testCode: 'FUNDOSCOPY_TEST', section: 'Fundoscopy Test', type: 'Main', field: 'Remarks', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
];
