import type { MedicalFieldConfig } from './medicalFieldConfig';

export const specialMedicalViewFieldConfig: MedicalFieldConfig[] = [
  { row: 2, id: 'special_view_2', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 3, id: 'special_view_3', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 4, id: 'special_view_4', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Value', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 5, id: 'special_view_5', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 6, id: 'special_view_6', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 7, id: 'special_view_7', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 8, id: 'special_view_8', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 9, id: 'special_view_9', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 10, id: 'special_view_10', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 11, id: 'special_view_11', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 12, id: 'special_view_12', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 13, id: 'special_view_13', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 14, id: 'special_view_14', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 15, id: 'special_view_15', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 16, id: 'special_view_16', testCode: 'BLOOD_SUGAR_RANDOM', section: 'Blood Sugar Random', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 17, id: 'special_view_17', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 18, id: 'special_view_18', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 19, id: 'special_view_19', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 20, id: 'special_view_20', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 21, id: 'special_view_21', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 22, id: 'special_view_22', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 23, id: 'special_view_23', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 24, id: 'special_view_24', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 25, id: 'special_view_25', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 26, id: 'special_view_26', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 28, id: 'special_view_28', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Hemoglobin(Hb)', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 29, id: 'special_view_29', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'RBC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 30, id: 'special_view_30', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'WBC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 31, id: 'special_view_31', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Platelets', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 32, id: 'special_view_32', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'PCV', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 33, id: 'special_view_33', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'MCV', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 34, id: 'special_view_34', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Differential_Neutrophil', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 35, id: 'special_view_35', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Differential_Lymphocyte', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 36, id: 'special_view_36', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Differential_Eosinophil', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 37, id: 'special_view_37', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Differential_Monocyte', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 38, id: 'special_view_38', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Differential_Basophil', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 39, id: 'special_view_39', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Esr', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 40, id: 'special_view_40', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Absolute_Neutrophil', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 41, id: 'special_view_41', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Absolute_Lymphocyte', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 42, id: 'special_view_42', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Absolute_Eosinophil', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 43, id: 'special_view_43', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Absolute_Monocyte', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 44, id: 'special_view_44', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Absolute_Basophil', dataType: 'Numerical', options: '', mandatory: 'Differential or Absolute any one mandatory' },
  { row: 45, id: 'special_view_45', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'MPV', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 46, id: 'special_view_46', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'PDW', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 47, id: 'special_view_47', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'MCH', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 48, id: 'special_view_48', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'MCHC', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 49, id: 'special_view_49', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'RDW', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 50, id: 'special_view_50', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'RBC_Morphology', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 51, id: 'special_view_51', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'WBC_Morphology', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 52, id: 'special_view_52', testCode: 'CBC_GROUP', section: 'CBC Group', type: 'Main', field: 'Platelet_Morphology', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 53, id: 'special_view_53', testCode: 'COT', section: 'COT', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 54, id: 'special_view_54', testCode: 'COT', section: 'COT', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 55, id: 'special_view_55', testCode: 'COT', section: 'COT', type: 'Main', field: 'Value', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Mandatory' },
  { row: 56, id: 'special_view_56', testCode: 'COT', section: 'COT', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 57, id: 'special_view_57', testCode: 'COT', section: 'COT', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 58, id: 'special_view_58', testCode: 'COT', section: 'COT', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 59, id: 'special_view_59', testCode: 'COT', section: 'COT', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 60, id: 'special_view_60', testCode: 'COT', section: 'COT', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 61, id: 'special_view_61', testCode: 'COT', section: 'COT', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 62, id: 'special_view_62', testCode: 'COT', section: 'COT', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 63, id: 'special_view_63', testCode: 'COT', section: 'COT', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 64, id: 'special_view_64', testCode: 'COT', section: 'COT', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 65, id: 'special_view_65', testCode: 'COT', section: 'COT', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 66, id: 'special_view_66', testCode: 'COT', section: 'COT', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 67, id: 'special_view_67', testCode: 'COT', section: 'COT', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 68, id: 'special_view_68', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 69, id: 'special_view_69', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 70, id: 'special_view_70', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Value', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 71, id: 'special_view_71', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 72, id: 'special_view_72', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Examinee Name', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 73, id: 'special_view_73', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 74, id: 'special_view_74', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 75, id: 'special_view_75', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 76, id: 'special_view_76', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 77, id: 'special_view_77', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 78, id: 'special_view_78', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 79, id: 'special_view_79', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 80, id: 'special_view_80', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 81, id: 'special_view_81', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 82, id: 'special_view_82', testCode: 'GHB', section: 'GHB', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 83, id: 'special_view_83', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 84, id: 'special_view_84', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 85, id: 'special_view_85', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Value', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 86, id: 'special_view_86', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 87, id: 'special_view_87', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 88, id: 'special_view_88', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 89, id: 'special_view_89', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 90, id: 'special_view_90', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 91, id: 'special_view_91', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 92, id: 'special_view_92', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 93, id: 'special_view_93', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 94, id: 'special_view_94', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 95, id: 'special_view_95', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 96, id: 'special_view_96', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 97, id: 'special_view_97', testCode: 'HBA1C', section: 'HBA1C', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 98, id: 'special_view_98', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 99, id: 'special_view_99', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 100, id: 'special_view_100', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Value', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Mandatory' },
  { row: 101, id: 'special_view_101', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 102, id: 'special_view_102', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 103, id: 'special_view_103', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 104, id: 'special_view_104', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 105, id: 'special_view_105', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 106, id: 'special_view_106', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 107, id: 'special_view_107', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 108, id: 'special_view_108', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 109, id: 'special_view_109', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 110, id: 'special_view_110', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 111, id: 'special_view_111', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 112, id: 'special_view_112', testCode: 'HBSAG', section: 'HBSAG', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 113, id: 'special_view_113', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nREGULAR MEDICAL\nPAST MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 114, id: 'special_view_114', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 115, id: 'special_view_115', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Value', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Mandatory' },
  { row: 116, id: 'special_view_116', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 117, id: 'special_view_117', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 118, id: 'special_view_118', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 119, id: 'special_view_119', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 120, id: 'special_view_120', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 121, id: 'special_view_121', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 122, id: 'special_view_122', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 123, id: 'special_view_123', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 124, id: 'special_view_124', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 125, id: 'special_view_125', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 126, id: 'special_view_126', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 127, id: 'special_view_127', testCode: 'HIV_ELISA', section: 'HIV Elisa', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 128, id: 'special_view_128', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Medical type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 129, id: 'special_view_129', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 130, id: 'special_view_130', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 131, id: 'special_view_131', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 132, id: 'special_view_132', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 133, id: 'special_view_133', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 134, id: 'special_view_134', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 135, id: 'special_view_135', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 136, id: 'special_view_136', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 137, id: 'special_view_137', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 139, id: 'special_view_139', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'SGPT/ALT', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 140, id: 'special_view_140', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'SGOT/AST', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 141, id: 'special_view_141', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'GGT', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 142, id: 'special_view_142', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Serum Bilirubin-Total', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 143, id: 'special_view_143', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Direct', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 144, id: 'special_view_144', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Indirect', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 145, id: 'special_view_145', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Serum Protein- Total', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 146, id: 'special_view_146', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Albumin', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 147, id: 'special_view_147', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Globulin=(Total-Albumin)', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 148, id: 'special_view_148', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Alkaline Phosphate', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 149, id: 'special_view_149', testCode: 'LFT', section: 'LFT', type: 'Main', field: 'Albumin/Globulin_Ratio', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 150, id: 'special_view_150', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 151, id: 'special_view_151', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 152, id: 'special_view_152', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 153, id: 'special_view_153', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 154, id: 'special_view_154', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 155, id: 'special_view_155', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 156, id: 'special_view_156', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 157, id: 'special_view_157', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 158, id: 'special_view_158', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 159, id: 'special_view_159', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 161, id: 'special_view_161', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Total Cholesterol: TC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 162, id: 'special_view_162', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'Triglycerides: TG', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 163, id: 'special_view_163', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'HDL', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 164, id: 'special_view_164', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'LDL', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 165, id: 'special_view_165', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'VLDL', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 166, id: 'special_view_166', testCode: 'LIPIDS', section: 'LIPIDS', type: 'Main', field: 'TC/HDL Ratio', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 167, id: 'special_view_167', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 168, id: 'special_view_168', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 169, id: 'special_view_169', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 170, id: 'special_view_170', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 171, id: 'special_view_171', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 172, id: 'special_view_172', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 173, id: 'special_view_173', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 174, id: 'special_view_174', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 175, id: 'special_view_175', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 176, id: 'special_view_176', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 178, id: 'special_view_178', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'OGTT1', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 179, id: 'special_view_179', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'OGTT2', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 180, id: 'special_view_180', testCode: 'OGTT_GROUP', section: 'OGTT Group', type: 'Main', field: 'OGTT3', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 181, id: 'special_view_181', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 182, id: 'special_view_182', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 183, id: 'special_view_183', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Value', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 184, id: 'special_view_184', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 185, id: 'special_view_185', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 186, id: 'special_view_186', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 187, id: 'special_view_187', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 188, id: 'special_view_188', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 189, id: 'special_view_189', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 190, id: 'special_view_190', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 191, id: 'special_view_191', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 192, id: 'special_view_192', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 193, id: 'special_view_193', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 194, id: 'special_view_194', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 195, id: 'special_view_195', testCode: 'PPBS', section: 'PPBS', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 196, id: 'special_view_196', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 197, id: 'special_view_197', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 198, id: 'special_view_198', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 199, id: 'special_view_199', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 200, id: 'special_view_200', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 201, id: 'special_view_201', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 202, id: 'special_view_202', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 203, id: 'special_view_203', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 204, id: 'special_view_204', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 205, id: 'special_view_205', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 207, id: 'special_view_207', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Sugar/Glycosuria', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent\nTrace\n+\n++\n+++\n++++', mandatory: 'Mandatory' },
  { row: 208, id: 'special_view_208', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Albumin/Proteinuria', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent\nTrace/+-\nMid/+\nModerate/++\nMarked/+++', mandatory: 'Mandatory' },
  { row: 209, id: 'special_view_209', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'RBC/Haematuria', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent/Occ\nTrace/+-/1-4\nMild/+/5-9\nModerate/++/10-19\nMarked /+++/>=20', mandatory: 'Mandatory' },
  { row: 210, id: 'special_view_210', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'WBC/PUS/Pyuria', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 211, id: 'special_view_211', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Epithelial Cells', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 212, id: 'special_view_212', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Gravity', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 213, id: 'special_view_213', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Ketone Bodies', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPresent\nNil/Absent', mandatory: 'Mandatory' },
  { row: 214, id: 'special_view_214', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Colour', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPale Yellow\nTransparent\nClear\nColourless\nDarker yellow\nDark orange or Brown\nDark brown or Black\nPink or Red\nBlue or Green\nCloudy\nWhite or Milky\nOther colour', mandatory: 'Non-Mandatory' },
  { row: 215, id: 'special_view_215', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_PH', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 216, id: 'special_view_216', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Quantity', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 217, id: 'special_view_217', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Appearance', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nClear\nCloudy\nTurbid\nDark Yellow', mandatory: 'Non-Mandatory' },
  { row: 218, id: 'special_view_218', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Blood', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Non-Mandatory' },
  { row: 219, id: 'special_view_219', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Nitrite', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Non-Mandatory' },
  { row: 220, id: 'special_view_220', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Bile_Salts', dataType: 'Dopdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', options: '', mandatory: 'Non-Mandatory' },
  { row: 221, id: 'special_view_221', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Bile_Pigment', dataType: 'Dropdown', options: 'Dropdown \n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Non-Mandatory' },
  { row: 222, id: 'special_view_222', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Bilirubin', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Non-Mandatory' },
  { row: 223, id: 'special_view_223', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Urobilinogen', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent/Normal\nPresent/Abnormal', mandatory: 'Non-Mandatory' },
  { row: 224, id: 'special_view_224', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Bacteria', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent\nPresent', mandatory: 'Non-Mandatory' },
  { row: 225, id: 'special_view_225', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Casts', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent\nPresent', mandatory: 'Non-Mandatory' },
  { row: 226, id: 'special_view_226', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Crystal', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent\nPresent', mandatory: 'Non-Mandatory' },
  { row: 227, id: 'special_view_227', testCode: 'RUA_GROUP', section: 'RUA Group', type: 'Main', field: 'Urine_Deposit', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNil/Absent\nPresent', mandatory: 'Non-Mandatory' },
  { row: 228, id: 'special_view_228', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL \nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 229, id: 'special_view_229', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 230, id: 'special_view_230', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Value', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive', mandatory: 'Mandatory' },
  { row: 231, id: 'special_view_231', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 232, id: 'special_view_232', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 233, id: 'special_view_233', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 234, id: 'special_view_234', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 235, id: 'special_view_235', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 236, id: 'special_view_236', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 237, id: 'special_view_237', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 238, id: 'special_view_238', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 239, id: 'special_view_239', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 240, id: 'special_view_240', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 241, id: 'special_view_241', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 242, id: 'special_view_242', testCode: 'SERUM_COTININE', section: 'SERUM COTININE', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 243, id: 'special_view_243', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 244, id: 'special_view_244', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 245, id: 'special_view_245', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 246, id: 'special_view_246', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 247, id: 'special_view_247', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 248, id: 'special_view_248', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 249, id: 'special_view_249', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 250, id: 'special_view_250', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 251, id: 'special_view_251', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 252, id: 'special_view_252', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 254, id: 'special_view_254', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'SGPT/ALT', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 255, id: 'special_view_255', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'SGOT/AST', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 256, id: 'special_view_256', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'GGT', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 257, id: 'special_view_257', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Serum Bilirubin-Total', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 258, id: 'special_view_258', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Direct', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 259, id: 'special_view_259', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Indirect=(Total-Direct)', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 260, id: 'special_view_260', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Serum Protein-Total', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 261, id: 'special_view_261', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Albumin', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 262, id: 'special_view_262', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Globulin=(Total-Albumin)', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 263, id: 'special_view_263', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Albumin/Globulin_Ratio', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 264, id: 'special_view_264', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Alkaline Phosphate', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 265, id: 'special_view_265', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Serum Creatinine', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 266, id: 'special_view_266', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Serum Calcium', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 267, id: 'special_view_267', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Serum Uric Acid', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 268, id: 'special_view_268', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'RBS', dataType: 'Numerical', options: '', mandatory: 'either FBS or RBS any one should be mandatory' },
  { row: 269, id: 'special_view_269', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'FBS', dataType: 'Numerical', options: '', mandatory: 'either FBS or RBS any one should be mandatory' },
  { row: 270, id: 'special_view_270', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Total Cholesterol: TC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 271, id: 'special_view_271', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'Triglycerides: TG', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 272, id: 'special_view_272', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'HDL', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 273, id: 'special_view_273', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'LDL', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 274, id: 'special_view_274', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'VLDL', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 275, id: 'special_view_275', testCode: 'SMA12_GROUP', section: 'SMA12 Group', type: 'Main', field: 'TC/HDL Ratio', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 276, id: 'special_view_276', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 277, id: 'special_view_277', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 278, id: 'special_view_278', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 279, id: 'special_view_279', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 280, id: 'special_view_280', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 281, id: 'special_view_281', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 282, id: 'special_view_282', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 283, id: 'special_view_283', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 284, id: 'special_view_284', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 285, id: 'special_view_285', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 287, id: 'special_view_287', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Triiodothyronine-T3', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 288, id: 'special_view_288', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Thyroxin-T4', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 289, id: 'special_view_289', testCode: 'TFT_GROUP', section: 'TFT Group', type: 'Main', field: 'Thyroid Stimulating - Tsh Harmones', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 290, id: 'special_view_290', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 291, id: 'special_view_291', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 292, id: 'special_view_292', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Value', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 293, id: 'special_view_293', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 294, id: 'special_view_294', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Examinee Name', dataType: 'Free text', options: '', mandatory: 'Mandatory' },
  { row: 295, id: 'special_view_295', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 296, id: 'special_view_296', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 297, id: 'special_view_297', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 298, id: 'special_view_298', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 299, id: 'special_view_299', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 300, id: 'special_view_300', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Doctor Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 301, id: 'special_view_301', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Doctor Registration No', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 302, id: 'special_view_302', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 303, id: 'special_view_303', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 304, id: 'special_view_304', testCode: 'FBS', section: 'FBS', type: 'Main', field: 'Units Value', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 305, id: 'special_view_305', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 306, id: 'special_view_306', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 307, id: 'special_view_307', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 308, id: 'special_view_308', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 309, id: 'special_view_309', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 310, id: 'special_view_310', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 311, id: 'special_view_311', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 312, id: 'special_view_312', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 313, id: 'special_view_313', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Doctor Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 314, id: 'special_view_314', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Doctor Registration No', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 316, id: 'special_view_316', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'SGPT/ALT', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 317, id: 'special_view_317', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'SGOT/AST', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 318, id: 'special_view_318', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'GGT', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 319, id: 'special_view_319', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Serum Bilirubin-Total', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 320, id: 'special_view_320', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Direct', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 321, id: 'special_view_321', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Indirect=(Total-Direct)', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 322, id: 'special_view_322', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Serum Protein-Total', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 323, id: 'special_view_323', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Albumin', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 324, id: 'special_view_324', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Globulin=(Total-Albumin)', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 325, id: 'special_view_325', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Albumin/Globulin_Ratio', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 326, id: 'special_view_326', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Alkaline Phosphate', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 327, id: 'special_view_327', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Serum Creatinine', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 328, id: 'special_view_328', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Serum Calcium', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 329, id: 'special_view_329', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Serum Uric Acid', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 330, id: 'special_view_330', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'RBS', dataType: 'Numerical', options: '', mandatory: 'either FBS or RBS any one should be mandatory' },
  { row: 331, id: 'special_view_331', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'FBS', dataType: 'Numerical', options: '', mandatory: 'either FBS or RBS any one should be mandatory' },
  { row: 332, id: 'special_view_332', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Total Cholesterol: TC', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 333, id: 'special_view_333', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'Triglycerides: TG', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 334, id: 'special_view_334', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'HDL', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 335, id: 'special_view_335', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'LDL', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 336, id: 'special_view_336', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'VLDL', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 337, id: 'special_view_337', testCode: 'S13_GROUP', section: 'S13 Group', type: 'Main', field: 'TC/HDL Ratio', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 338, id: 'special_view_338', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nREGULAR MEDICAL\nPAST MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 339, id: 'special_view_339', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 340, id: 'special_view_340', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Value', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Mandatory' },
  { row: 341, id: 'special_view_341', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 342, id: 'special_view_342', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Examinee Name', dataType: 'Free text', options: '', mandatory: 'Mandatory' },
  { row: 343, id: 'special_view_343', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 344, id: 'special_view_344', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 345, id: 'special_view_345', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 346, id: 'special_view_346', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 347, id: 'special_view_347', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 348, id: 'special_view_348', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Doctor Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 349, id: 'special_view_349', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Doctor Registration No', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 350, id: 'special_view_350', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 351, id: 'special_view_351', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 352, id: 'special_view_352', testCode: 'HIV_WESTERN_BLOT', section: 'HIV Western Blot', type: 'Main', field: 'Units Value', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 353, id: 'special_view_353', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nREGULAR MEDICAL\nPAST MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 354, id: 'special_view_354', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 355, id: 'special_view_355', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Value', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nNegative/Non Reactive\nPositive/Reactive', mandatory: 'Mandatory' },
  { row: 356, id: 'special_view_356', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Findings', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 357, id: 'special_view_357', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 358, id: 'special_view_358', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 359, id: 'special_view_359', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 360, id: 'special_view_360', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 361, id: 'special_view_361', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 362, id: 'special_view_362', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 363, id: 'special_view_363', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 364, id: 'special_view_364', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 365, id: 'special_view_365', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 366, id: 'special_view_366', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 367, id: 'special_view_367', testCode: 'HCV', section: 'HCV', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 368, id: 'special_view_368', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 369, id: 'special_view_369', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 370, id: 'special_view_370', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Findings', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 371, id: 'special_view_371', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 372, id: 'special_view_372', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 373, id: 'special_view_373', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 374, id: 'special_view_374', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 375, id: 'special_view_375', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 376, id: 'special_view_376', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 377, id: 'special_view_377', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 378, id: 'special_view_378', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Doctor Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 379, id: 'special_view_379', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Doctor Registration No', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 380, id: 'special_view_380', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 381, id: 'special_view_381', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 382, id: 'special_view_382', testCode: 'MICROALBUMINURIA', section: 'MICROALBUMINURIA', type: 'Main', field: 'Units Value', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 383, id: 'special_view_383', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Medical Type', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nPAST MEDICAL\nREGULAR MEDICAL', mandatory: 'Non-Mandatory' },
  { row: 384, id: 'special_view_384', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Test Date', dataType: 'Calendar', options: '', mandatory: 'Non-Mandatory' },
  { row: 385, id: 'special_view_385', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Findings', dataType: 'Numerical', options: '', mandatory: 'Mandatory' },
  { row: 386, id: 'special_view_386', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Result', dataType: 'Auto-populated', options: '', mandatory: 'Auto-populated' },
  { row: 387, id: 'special_view_387', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Examinee Name', dataType: 'Free Text', options: '', mandatory: 'Mandatory' },
  { row: 388, id: 'special_view_388', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Examinee Age', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 389, id: 'special_view_389', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Examinee Gender', dataType: 'Dropdown', options: 'Dropdown\n--Select--\nMALE\nFEMALE\nTRANSGENDER', mandatory: 'Non-Mandatory' },
  { row: 390, id: 'special_view_390', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Diagnostic Centre Name', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 391, id: 'special_view_391', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Diagnostic Centre Address', dataType: 'Free Text', options: '', mandatory: 'Non-Mandatory' },
  { row: 392, id: 'special_view_392', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Diagnostic Centre Pincode', dataType: 'Numerical', options: '', mandatory: 'Non-Mandatory' },
  { row: 393, id: 'special_view_393', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Doctor Name', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 394, id: 'special_view_394', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Doctor Registration No', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 395, id: 'special_view_395', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Lab Range Value(Start range)', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 396, id: 'special_view_396', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Lab Range Value(End range)', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
  { row: 397, id: 'special_view_397', testCode: 'PSA', section: 'PSA', type: 'Main', field: 'Units Value', dataType: 'Free text', options: '', mandatory: 'Non-Mandatory' },
];
