import type { MasterKey } from "../../types/drs.types";

export const DRS_MASTER_KEYS: MasterKey[] = [
  "title",
  "gender",
  "nationality",
  "idProof",
  "addressProof",
  "state",
  "country",
  "maritalStatus",
  "pep",
  "exceptionDecision",
  "cvtDecision",
  "dvtDecision",
  "caseUWDecision",
  "firstUWDecision",
  "parallelUWDecision",
  "reconsiderationDecision",
  "riskDecision",
  "srUwDecision",
  "hodDecision",
  "hoCmoDecision",
  "reinsurerDecision",
  "reinsurerDecisionId",
  "pivvDecision",
  "rejectReason",
  "declineReason",
  "postponeReason",
  "postponementPeriod",
  "riskReferralReason",
  "accuityReferralReason",
  "reinsurerReferralReason",
  "holdReason",
  "cuwReferralReason",
  "resident_status", "marital_status", "education", "occupation", "industry_type", "organization_type", "id_proof_type", "impairement_type", "insurance_repository", "product", "rider", "annuity_option", "fund", "portfolio_strategy", "payment_mode", "source_of_fund", "proposal_status", "country", "state", "policy_decision", "agent_mst", "health_question", "bre", "ntu_retail", "pre_post_insurance", "uw_decision", "app_status", "misc","requirement_mst","decision_master","requirement_status_master", "reason","medical"
];