import type { MasterKey } from "../../types/drs.types";

export const DRS_MASTER_KEYS: MasterKey[] = [
  "title",
  "gender",
  "nationality",
  "idProof",
  "addressProof",
  "state",
  "country",
  "maritalStatus",
  "pep",
  "exceptionDecision",
  "requirementManagement",
  "requirementTeam",
  "requirementProfile",
  "requirementCategory",
  "requirementSubCategory",
  "requirementDocument",
  "requirementReason",
  "requirementStatus",
  "cvtDecision",
  "dvtDecision",
  "caseUWDecision",
  "firstUWDecision",
  "parallelUWDecision",
  "reconsiderationDecision",
  "rejectReason",
  "declineReason",
  "postponeReason",
  "postponementPeriod",
  "riskReferralReason",
  "accuityReferralReason",
  "reinsurerReferralReason",
  "holdReason",
  "cuwReferralReason",
];