export type FinancialField = {
  label: string;
  value?: string | number | boolean;
  isMandatory?: boolean;
  mandatoryCondition?: string;
};

export type FinancialSectionKey =
  // | "advanceTaxChallan"
  | "appointmentLetter"
  | "caCertifiedBalanceSheet"
  | "caCertifiedNetWorthStatement"
  | "commissionStatement"
  | "computationOfIncome"
  | "creditCards"
  | "fixedDepositReceipt"
  | "form16"
  | "form16a"
  | "formJ"
  | "governmentOfIndiaBonds"
  | "incomeTaxReturnNonIndividual"
  | "incomeTaxReturnIndividual"
  | "loanStatements"
  | "mutualFundAccountStatement"
  | "pensionStatement"
  | "profitAndLossAccount"
  | "propertyPurchaseDocuments"
  | "propertyValuationReport"
  | "salaryCertificate"
  | "salaryRevisionLetter"
  | "salarySlips"
  | "savingsAccountStatements"
  | "stockHoldingStatement"
  | "vehicleOwnershipPapers"
  | "vahan"
  | "sipStatement"
  | "gstIncome"
  | "bankStatementSalaryCredit"
  | "epfBasic"
  | "epfAdvanced";

export type FinancialSectionConfig = {
  key: FinancialSectionKey;
  title: string;
  columns?: number;
  items: FinancialField[];
};

const section = (
  key: FinancialSectionKey,
  title: string,
  items: FinancialField[],
  columns = 3,
): FinancialSectionConfig => ({
  key,
  title,
  columns,
  items,
});

export const financialSections: FinancialSectionConfig[] = [
  // section("advanceTaxChallan", "ADVANCE TAX CHALLAN", [
  //   { label: "Assesse", value: "No" },
  //   { label: "Period", value: "No" },
  //   { label: "Advance Tax", value: "No" },
  //   { label: "Total Tax Liability", value: "No" },
  //   { label: "Derived Income", value: "Yes" },
  // ]),
  section("appointmentLetter", "Appointment Letter / Contract of Employer", [
    { label: "Gross Salary PA", value: "" },
    {label: "Name of the company", value: "ABCD Company"},
    {label: "Joining Date", value: "22/06/2024", isMandatory: true},
    {label: "CTC", value: "500000", isMandatory: true},
  ]),
  section("caCertifiedBalanceSheet", "CA Certified Balance Sheet", [
    { label: "Is Balance Sheet in the name of LA", value: "No" },
    { label: "Fixed Assets", value: "No" },
    { label: "Other Investments", value: "No" },
    { label: "Cash", value: "No" },
    { label: "Banks", value: "No" },
    { label: "Secured Loans", value: "No" },
    { label: "Net Worth", value: "No" },
    { label: "Derived Income", value: "Yes" },
    { label: "Average Income", value: "Auto calculate" },
  ]),
  section("caCertifiedNetWorthStatement", "CA Certified Net Worth Statement", [
    { label: "Is Net Worth Statement in the name of LA", value: "No" },
    { label: "Is Certified by CA", value: "No" },
    { label: "Net Worth as per Statement", value: "No" },
    { label: "Income Earned", value: "No" },
    { label: "Derived Income", value: "Yes" },
    { label: "Average Income", value: "Auto calculate" },
  ]),
  section("commissionStatement", "Commission Statement", [
    { label: "Month 1", value: "10000", isMandatory: true },
    { label: "Month 2", value: "20000" },
    { label: "Month 3", value: "" },
    { label: "Month 4", value: "" },
    { label: "Month 5", value: "" },
    { label: "Month 6", value: "" },
    { label: "Average commission pm", value: "15000" },
    { label: "Average Annual Income", value: "180000" },
  ], 4),
  // section("computationOfIncome", "Computation Of Income", [
  //   { label: "Assessment Year", value: "at least One Year data Mandatory" },
  //   { label: "Income from Salary(A)", value: "atleast Income from salary or Income from Business or Exempt Income mandatory" },
  //   { label: "Income from House Property", value: "No" },
  //   { label: "Income from Business or Profession (B)", value: "atleast Income from salary or Income from Business or Exempt Income mandatory" },
  //   { label: "Short term & Capital Gains", value: "No" },
  //   { label: "Income from Other Sources", value: "No" },
  //   { label: "Agricultural Income", value: "No" },
  //   { label: "Exempt Income(C)", value: "atleast Income from salary or Income from Business or Exempt Income mandatory" },
  //   { label: "Gross Total Income", value: "Auto calculate" },
  //   { label: "Total Gross Total Income", value: "Auto calculate" },
  //   { label: "Average Gross Total Income", value: "Auto calculate" },
  // ], 3),
  section("creditCards", "Credit Cards", [
    { label: "Is Credit card statement in the name of LA", value: "" },
    { label: "Is LA Defaulter in the Payment", value: "" },
    { label: "Type of Card", value: "" },
    { label: "Credit Limit", value: "50000", isMandatory: true },
    { label: "Points Earned", value: "" },
    { label: "Income Earned", value: "" },
    { label: "Derived Income", value: "100000" },
    { label: "Average Income", value: "100000" },
  ]),
  section("fixedDepositReceipt", "Fixed Deposit Receipt", [
    { label: "Is Fixed Deposit Receipt in the name of LA", value: "" },
    { label: "Is Fixed Deposit Receipts matured", value: "" },
    { label: "Amount Invested", value: "100000", isMandatory: true },
    { label: "Income Earned", value: "" },
    { label: "Derived Income", value: "50000" },
    { label: "Average Income", value: "50000" },
  ]),
  section("form16", "FORM16/FORM 130", [
    { label: "Entity", value: "Year 1 | Year 2 | Year 3" },
    { label: "ASSESSMENT", value: "AY 25-26", isMandatory: true },
    { label: "ASSESSMENT Year 2", value: "AY 24-25", isMandatory: true },
    { label: "ASSESSMENT Year 3", value: "AY 23-24", isMandatory: true },
    { label: "Gross Salary PA", value: "500000" },
    { label: "Gross Salary PA Year 2", value: "460000" },
    { label: "Gross Salary PA Year 3", value: "420000" },
    { label: "Average Annual Income", value: "460000" },
    { label: "Average Annual Income Year 2", value: "430000" },
    { label: "Average Annual Income Year 3", value: "400000" },
    { label: "Life Assured Pan No", value: "AXXXDXXX2L" },
    { label: "Life Assured Pan No Year 2", value: "AXXXDXXX2L" },
    { label: "Life Assured Pan No Year 3", value: "AXXXDXXX2L" },
    { label: "Life Assured Name", value: "Rudra Sangha" },
    { label: "Life Assured Name Year 2", value: "Rudra Sangha" },
    { label: "Life Assured Name Year 3", value: "Rudra Sangha" },
    { label: "Is Life Assured Name Same With Doc Name?", value: "No" },
    { label: "Company Name", value: "ICICI Bank" },
  ], 3),
  section("form16a", "FORM 16A/FORM 131", [
    { label: "Assessment Year", value: "AY 25-26", isMandatory: true },
    { label: "Assessment Year Year 2", value: "Latest 1 Year data Mandatory", isMandatory: true },
    { label: "Assessment Year Year 3", value: "AY 23-24", isMandatory: true },
    { label: "Net Receipt pa", value: "Yes", isMandatory: true },
    { label: "Net Receipt pa Year 2", value: "No" },
    { label: "Net Receipt pa Year 3", value: "No" },
    { label: "Average Annual Income", value: "10000", isMandatory: true },
    { label: "Average Annual Income Year 2", value: "" },
    { label: "Average Annual Income Year 3", value: "" },
  ], 3),
  // section("formJ", "FORM J", [
  //   { label: "Is Form J in the name of LA", value: "" },
  //   { label: "Month 1", value: "at least One month and one receipt data Mandatory" },
  //   { label: "Month 2", value: "" },
  //   { label: "Month 3", value: "" },
  //   { label: "Total Receipts", value: "Auto calculate" },
  //   { label: "Average Monthly Receipts", value: "Auto calculate" },
  //   { label: "Annual Receipts", value: "Auto calculate" },
  //   { label: "Derived Income", value: "Auto calculate" },
  // ]),
  section("formJ", "FORM J", [
    { label: "Is Form J in the name of LA", value: "No", isMandatory: true },
    { label: "Month1 Receipt1", value: "10000", isMandatory: true },
    { label: "Month1 Receipt2", value: "" },
    { label: "Month1 Receipt3", value: "" },
    { label: "Month1 Receipt4", value: "" },
    { label: "Month1 Receipt5", value: "" },
    { label: "Month1 Receipt6", value: "" },
    { label: "Month2 Receipt1", value: "12000" },
    { label: "Month2 Receipt2", value: "" },
    { label: "Month2 Receipt3", value: "" },
    { label: "Month2 Receipt4", value: "" },
    { label: "Month2 Receipt5", value: "" },
    { label: "Month2 Receipt6", value: "" },
    { label: "Month3 Receipt1", value: "14000" },
    { label: "Month3 Receipt2", value: "" },
    { label: "Month3 Receipt3", value: "" },
    { label: "Month3 Receipt4", value: "" },
    { label: "Month3 Receipt5", value: "" },
    { label: "Month3 Receipt6", value: "" },
    { label: "Total Receipts Receipt1", value: "10000", isMandatory: true },
    { label: "Total Receipts Receipt2", value: "" },
    { label: "Total Receipts Receipt3", value: "" },
    { label: "Total Receipts Receipt4", value: "" },
    { label: "Total Receipts Receipt5", value: "" },
    { label: "Total Receipts Receipt6", value: "" },
    { label: "Average Monthly Receipts Receipt1", value: "12000", isMandatory: true },
    { label: "Average Monthly Receipts Receipt2", value: "" },
    { label: "Average Monthly Receipts Receipt3", value: "" },
    { label: "Average Monthly Receipts Receipt4", value: "" },
    { label: "Average Monthly Receipts Receipt5", value: "" },
    { label: "Average Monthly Receipts Receipt6", value: "" },
    { label: "Annual Receipts Receipt1", value: "144000", isMandatory: true },
    { label: "Annual Receipts Receipt2", value: "" },
    { label: "Annual Receipts Receipt3", value: "" },
    { label: "Annual Receipts Receipt4", value: "" },
    { label: "Annual Receipts Receipt5", value: "" },
    { label: "Annual Receipts Receipt6", value: "" },
    { label: "Derived Income Receipt1", value: "144000", isMandatory: true },
    { label: "Derived Income Receipt2", value: "" },
    { label: "Derived Income Receipt3", value: "" },
    { label: "Derived Income Receipt4", value: "" },
    { label: "Derived Income Receipt5", value: "" },
    { label: "Derived Income Receipt6", value: "" },
  ], 3),
  section("governmentOfIndiaBonds", "Govt. Of India Bonds", [
    { label: "Is Bond Certification in the name of LA", value: "" },
    { label: "Is Bond Certificate matured", value: "" },
    { label: "Amount Invested or Maturity Value, whichever higher", value: "10000", isMandatory: true },
    { label: "Income Earned", value: "" },
    { label: "Derived Income", value: "5000" },
    { label: "Average Income", value: "5000" },
  ]),
  // section("incomeTaxReturnNonIndividual", "Income Tax Return (Non-Individual)", [
  //   { label: "Name of Organisation/Firm", value: "No" },
  //   { label: "Permanent Account Number", value: "No" },
  //   { label: "ITR Acknowledgement Number", value: "No" },
  //   { label: "Assessment Year", value: "at least One Year data Mandatory" },
  //   { label: "Income from Salary", value: "atleast one field data Mandatory" },
  //   { label: "Income from House Property", value: "" },
  //   { label: "Income from Business or Profession", value: "" },
  //   { label: "Short term & Capital Gains", value: "" },
  //   { label: "Income from Other Sources", value: "" },
  //   { label: "Agricultural Income", value: "" },
  //   { label: "Exempt Income", value: "" },
  //   { label: "Gross Total Income", value: "Auto calculate" },
  //   { label: "Total Gross Total Income", value: "Auto calculate" },
  //   { label: "Average Gross Total Income", value: "Auto calculate" },
  // ], 3),
  section("incomeTaxReturnNonIndividual", "Income Tax Return (Non-Individual)", [
    { label: "Name of Organisation/Firm", value: "No", isMandatory: true },
    { label: "Permanent Account Number", value: "No", isMandatory: true },
    { label: "Assessment Year", value: "AY 25-26", isMandatory: true },
    { label: "Assessment Year Year 2", value: "Latest 2 Years field data Mandatory", isMandatory: true },
    { label: "Assessment Year Year 3", value: "AY 23-24", isMandatory: true },
    { label: "ITR Acknowledgement Number", value: "No", isMandatory: true },
    { label: "Income from Salary", value: "10000", isMandatory: true },
    { label: "Income from Salary Year 2", value: "" },
    { label: "Income from Salary Year 3", value: "" },
    { label: "Income from House Property", value: "No" },
    { label: "Income from House Property Year 2", value: "" },
    { label: "Income from House Property Year 3", value: "" },
    { label: "Income from Business or Profession", value: "10000", isMandatory: true },
    { label: "Income from Business or Profession Year 2", value: "" },
    { label: "Income from Business or Profession Year 3", value: "" },
    { label: "Short term & Capital Gains", value: "No" },
    { label: "Short term & Capital Gains Year 2", value: "" },
    { label: "Short term & Capital Gains Year 3", value: "" },
    { label: "Income from Other Sources", value: "No" },
    { label: "Income from Other Sources Year 2", value: "" },
    { label: "Income from Other Sources Year 3", value: "" },
    { label: "Agricultural Income", value: "No" },
    { label: "Agricultural Income Year 2", value: "" },
    { label: "Agricultural Income Year 3", value: "" },
    { label: "Exempt Income", value: "5000", isMandatory: true },
    { label: "Exempt Income Year 2", value: "" },
    { label: "Exempt Income Year 3", value: "" },
    { label: "Gross Total Income", value: "250000", isMandatory: true },
    { label: "Gross Total Income Year 2", value: "" },
    { label: "Gross Total Income Year 3", value: "" },
    { label: "Total Gross Total Income", value: "250000", isMandatory: true },
    { label: "Total Gross Total Income Year 2", value: "" },
    { label: "Total Gross Total Income Year 3", value: "" },
    { label: "Average Gross Total Income", value: "120000", isMandatory: true },
    { label: "Average Gross Total Income Year 2", value: "" },
    { label: "Average Gross Total Income Year 3", value: "" },
  ], 3),
  // section("incomeTaxReturnIndividual", "Income Tax Return (Individual)", [
  //   { label: "Name of Organisation/Firm", value: "No" },
  //   { label: "Permanent Account Number", value: "No" },
  //   { label: "ITR Acknowledgement Number", value: "No" },
  //   { label: "Assessment Year", value: "at least One Year data Mandatory" },
  //   { label: "Date of Filling ITR", value: "No" },
  //   { label: "Income from Salary(A)", value: "atleast Income from salary or Income from Business or Exempt Income" },
  //   { label: "Income from House Property", value: "No" },
  //   { label: "Income from Business or Profession(B)", value: "atleast Income from salary or Income from Business or Exempt Income" },
  //   { label: "Short term & Capital Gains", value: "No" },
  //   { label: "Income from Other Sources", value: "No" },
  //   { label: "Agricultural Income", value: "No" },
  //   { label: "Exempt Income(C)", value: "atleast Income from salary or Income from Business or Exempt Income" },
  //   { label: "Gross Total Income(A+B+C)", value: "Auto calculate" },
  //   { label: "Total Gross Total Income", value: "Auto calculate" },
  //   { label: "Average Gross Total Income", value: "Auto calculate" },
  //   { label: "PF deduction - Salaried customers", value: "No" },
  //   { label: "Life Assured Name", value: "Yes" },
  //   { label: "Is Life Assured Name Same?", value: "Yes" },
  // ], 3),
  section("incomeTaxReturnIndividual", "Income Tax Return (Individual)", [
    { label: "Name of Organisation/Firm", value: "No", isMandatory: true },
    { label: "Permanent Account Number", value: "No", isMandatory: true },
    { label: "Assessment Year", value: "AY 25-26", isMandatory: true },
    { label: "Assessment Year Year 2", value: "Latest 2 Years field data Mandatory", isMandatory: true },
    { label: "Assessment Year Year 3", value: "AY 23-24", isMandatory: true },
    { label: "ITR Acknowledgement Number", value: "No", isMandatory: true },
    { label: "Date of Filling ITR", value: "Yes", isMandatory: true },
    { label: "Date of Filling ITR Year 2", value: "" },
    { label: "Date of Filling ITR Year 3", value: "" },
    { label: "Income from Salary(A)", value: "100000", isMandatory: true },
    { label: "Income from Salary(A) Year 2", value: "" },
    { label: "Income from Salary(A) Year 3", value: "" },
    { label: "Income from House Property", value: "No" },
    { label: "Income from House Property Year 2", value: "" },
    { label: "Income from House Property Year 3", value: "" },
    { label: "Income from Business or Profession(B)", value: "100000", isMandatory: true },
    { label: "Income from Business or Profession(B) Year 2", value: "" },
    { label: "Income from Business or Profession(B) Year 3", value: "" },
    { label: "Short term & Capital Gains", value: "No" },
    { label: "Short term & Capital Gains Year 2", value: "" },
    { label: "Short term & Capital Gains Year 3", value: "" },
    { label: "Income from Other Sources", value: "No" },
    { label: "Income from Other Sources Year 2", value: "" },
    { label: "Income from Other Sources Year 3", value: "" },
    { label: "Agricultural Income", value: "No" },
    { label: "Agricultural Income Year 2", value: "" },
    { label: "Agricultural Income Year 3", value: "" },
    { label: "Exempt Income(C)", value: "0", isMandatory: true },
    { label: "Exempt Income(C) Year 2", value: "" },
    { label: "Exempt Income(C) Year 3", value: "" },
    { label: "Gross Total Income(A+B+C)", value: "200000", isMandatory: true },
    { label: "Gross Total Income(A+B+C) Year 2", value: "" },
    { label: "Gross Total Income(A+B+C) Year 3", value: "" },
    { label: "Total Gross Total Income", value: "1200000", isMandatory: true },
    { label: "Total Gross Total Income Year 2", value: "" },
    { label: "Total Gross Total Income Year 3", value: "" },
    { label: "Average Gross Total Income", value: "1200000", isMandatory: true },
    { label: "Average Gross Total Income Year 2", value: "" },
    { label: "Average Gross Total Income Year 3", value: "" },
    { label: "PF deduction - Salaried customers", value: "No" },
    { label: "PF deduction - Salaried customers Year 2", value: "" },
    { label: "PF deduction - Salaried customers Year 3", value: "" },
    { label: "Life Assured Name", value: "Yes", isMandatory: true },
    { label: "Life Assured Name Year 2", value: "" },
    { label: "Life Assured Name Year 3", value: "" },
    { label: "Is Life Assured Name Same?", value: "Yes", isMandatory: true },
    { label: "Is Life Assured Name Same? Year 2", value: "" },
    { label: "Is Life Assured Name Same? Year 3", value: "" },
  ], 3),
  section("loanStatements", "Loan Statements", [
    { label: "Is Loan Statements in the name of LA", value: "" },
    { label: "Is LA Defaulter in the Payment", value: "" },
    { label: "Monthly EMI as per Schedule", value: "1000", isMandatory: true },
    { label: "Income Earned", value: "" },
    { label: "Derived Income", value: "24000" },
    { label: "Average Income", value: "24000" },
  ]),
  section("mutualFundAccountStatement", "Mutual Fund A/C Statement", [
    { label: "Is Mutual Fund Statement in the name of LA", value: "" },
    { label: "Latest Market Value (as per NAV) in Statement", value: "100000" },
    { label: "Income Earned", value: "" },
    { label: "Derived Income", value: "50000" },
    { label: "Average Income", value: "50000" },
  ]),
  section("pensionStatement", "PENSION STATEMENT", [
    { label: "Total Monthly Pension", value: "10000", isMandatory: true },
    { label: "Pension Received pa", value: "120000" },
  ]),
  // section("profitAndLossAccount", "Profit & Loss A/C", [
  //   { label: "Name of Organization/Firm", value: "Yes" },
  //   { label: "As Per Accounts of Proposer Co.", value: "Year 1 | Year 2 | Year 3" },
  //   { label: "Assessment Year", value: "at least One Year data Mandatory" },
  //   { label: "Shareholders Funds / Partners Capital", value: "" },
  //   { label: "Share Capital or Fixed/Fluctuating Capital", value: "No" },
  //   { label: "Reserves & Surplus", value: "No" },
  //   { label: "Total Shareholders Funds or Partner's Fund", value: "No" },
  //   { label: "Profit Before Depreciation & Tax (PBDT)", value: "No" },
  //   { label: "Less : Depreciation", value: "No" },
  //   { label: "Profit Before Tax (PBT)", value: "No" },
  //   { label: "Tax", value: "No" },
  //   { label: "Profit After Tax (PAT)", value: "Yes" },
  //   { label: "Profit After Tax of Last Year", value: "No" },
  //   { label: "Rise In Profit as compared to Last Year", value: "No" },
  //   { label: "% Rise In Profit as compared to Last Year", value: "No" },
  //   { label: "Sales", value: "No" },
  //   { label: "Sales of Last Year", value: "No" },
  //   { label: "Rise In Sales as compared to Last Year", value: "No" },
  //   { label: "% Rise In Sales as compared to Last Year", value: "No" },
  //   { label: "Average Gross Income", value: "Auto calculate" },
  //   { label: "Average Profit Before Tax", value: "No" },
  //   { label: "Average Profit After Tax", value: "No" },
  // ], 3),
  section("profitAndLossAccount", "Profit & Loss A/C", [
    { label: "Name of Organization/Firm", value: "Yes", isMandatory: true },
    { label: "As Per Accounts of Proposer Co.", value: "Year1", isMandatory: true },
    { label: "As Per Accounts of Proposer Co. Year 2", value: "Year2", isMandatory: true },
    { label: "As Per Accounts of Proposer Co. Year 3", value: "Year3", isMandatory: true },
    { label: "Assessment Year", value: "AY 25-26", isMandatory: true },
    { label: "Assessment Year Year 2", value: "Latest 3 Year Year data Mandatory", isMandatory: true },
    { label: "Assessment Year Year 3", value: "AY 23-24", isMandatory: true },
    { label: "Shareholders Funds / Partners Capital", value: "" },
    { label: "Shareholders Funds / Partners Capital Year 2", value: "" },
    { label: "Shareholders Funds / Partners Capital Year 3", value: "" },
    { label: "Share Capital or Fixed/Fluctuating Capital", value: "No" },
    { label: "Share Capital or Fixed/Fluctuating Capital Year 2", value: "" },
    { label: "Share Capital or Fixed/Fluctuating Capital Year 3", value: "" },
    { label: "Reserves & Surplus", value: "No" },
    { label: "Reserves & Surplus Year 2", value: "" },
    { label: "Reserves & Surplus Year 3", value: "" },
    { label: "Total Shareholders Funds or Partner's Fund", value: "No" },
    { label: "Total Shareholders Funds or Partner's Fund Year 2", value: "" },
    { label: "Total Shareholders Funds or Partner's Fund Year 3", value: "" },
    { label: "Profit Calculation", value: "" },
    { label: "Profit Calculation Year 2", value: "" },
    { label: "Profit Calculation Year 3", value: "" },
    { label: "Profit Before Depreciation & Tax (PBDT)", value: "No" },
    { label: "Profit Before Depreciation & Tax (PBDT) Year 2", value: "" },
    { label: "Profit Before Depreciation & Tax (PBDT) Year 3", value: "" },
    { label: "Less : Depreciation", value: "No" },
    { label: "Less : Depreciation Year 2", value: "" },
    { label: "Less : Depreciation Year 3", value: "" },
    { label: "Profit Before Tax (PBT)", value: "No" },
    { label: "Profit Before Tax (PBT) Year 2", value: "" },
    { label: "Profit Before Tax (PBT) Year 3", value: "" },
    { label: "Tax", value: "No" },
    { label: "Tax Year 2", value: "" },
    { label: "Tax Year 3", value: "" },
    { label: "Profit After Tax (PAT)", value: "Yes" },
    { label: "Profit After Tax (PAT) Year 2", value: "" },
    { label: "Profit After Tax (PAT) Year 3", value: "" },
    { label: "Profit After Tax of Last Year", value: "No" },
    { label: "Profit After Tax of Last Year Year 2", value: "" },
    { label: "Profit After Tax of Last Year Year 3", value: "" },
    { label: "Rise In Profit as compared to Last Year", value: "No" },
    { label: "Rise In Profit as compared to Last Year Year 2", value: "" },
    { label: "Rise In Profit as compared to Last Year Year 3", value: "" },
    { label: "% Rise In Profit as compared to Last Year", value: "No" },
    { label: "% Rise In Profit as compared to Last Year Year 2", value: "" },
    { label: "% Rise In Profit as compared to Last Year Year 3", value: "" },
    { label: "Income Calculation", value: "" },
    { label: "Income Calculation Year 2", value: "" },
    { label: "Income Calculation Year 3", value: "" },
    { label: "Sales", value: "No" },
    { label: "Sales Year 2", value: "" },
    { label: "Sales Year 3", value: "" },
    { label: "Sales of Last Year", value: "No" },
    { label: "Sales of Last Year Year 2", value: "" },
    { label: "Sales of Last Year Year 3", value: "" },
    { label: "Rise In Sales as compared to Last Year", value: "No" },
    { label: "Rise In Sales as compared to Last Year Year 2", value: "" },
    { label: "Rise In Sales as compared to Last Year Year 3", value: "" },
    { label: "% Rise In Sales as compared to Last Year", value: "No" },
    { label: "% Rise In Sales as compared to Last Year Year 2", value: "" },
    { label: "% Rise In Sales as compared to Last Year Year 3", value: "" },
    { label: "Average Gross Income", value: "Auto calculate", isMandatory: true },
    { label: "Average Gross Income Year 2", value: "" },
    { label: "Average Gross Income Year 3", value: "" },
    { label: "Average Profit Before Tax", value: "No" },
    { label: "Average Profit Before Tax Year 2", value: "" },
    { label: "Average Profit Before Tax Year 3", value: "" },
    { label: "Average Profit After Tax", value: "No" },
    { label: "Average Profit After Tax Year 2", value: "" },
    { label: "Average Profit After Tax Year 3", value: "" },
  ], 3),
  section("propertyPurchaseDocuments", "Property Purchase Documents", [
    { label: "Is Property purchased by LA", value: "" },
    { label: "Purchase Price", value: "100000", isMandatory: true },
    { label: "Financial Year of Purchase", value: "" },
    { label: "Estimated Market Value of Property", value: "" },
    { label: "Derived Income", value: "20000" },
  ]),
  section("propertyValuationReport", "Property Valuation Report", [
    { label: "Is Property Valuation Report in the name of LA", value: "" },
    { label: "Estimated Market Value of Property(as per report)", value: "100000", isMandatory: true },
    { label: "Derived Income", value: "20000" },
  ]),
  section("salaryCertificate", "Salary Certificate", [
    { label: "Gross Salary PA", value: "100000", isMandatory: true },
  ]),
  section("salaryRevisionLetter", "Salary Revision Letter", [
    { label: "Gross Salary PA", value: "100000", isMandatory: true },
  ]),
  section("salarySlips", "SALARY SLIPS", [
    { label: "Gross Salary Pm1", value: "50000", isMandatory: true },
    { label: "Gross Salary Pm2", value: "50000", isMandatory: true },
    { label: "Gross Salary Pm3", value: "50000", isMandatory: true },
    { label: "Gross Salary Pm4", value: "" },
    { label: "Gross Salary Pm5", value: "" },
    { label: "Gross Salary Pm6", value: "" },
    { label: "Average Salary pm", value: "50000" },
    { label: "Gross Salary pa", value: "50000" },
    { label: "Annual Bonus/Incentive/Reimbursement", value: "" },
    { label: "Average Annual Income", value: "600000" },
    { label: "Company Name", value: "ABCD Company", isMandatory: true },
    { label: "Life Assured Name", value: "Rajveer Shikhavat", isMandatory: true },
    { label: "Is Life Assured Name Same?", value: "Yes", isMandatory: true },
    { label: "PF / UAN No", value: "" },
  ], 3),
  section("savingsAccountStatements", "Savings A/C & Current A/C Bank Statements", [
    { label: "Is Bank Statement in the name of LA/his Business", value: "Yes", isMandatory: true },
    { label: "Latest 6 months statements given", value: "Yes", isMandatory: true },
    { label: "Any Overdraft(Negative/Debit) Balances", value: "Yes", isMandatory: true },
    { label: "Monthly Closing Bal 1", value: "600000", isMandatory: true },
    { label: "Monthly Closing Bal 2", value: "" },
    { label: "Monthly Closing Bal 3", value: "" },
    { label: "Monthly Closing Bal 4", value: "" },
    { label: "Monthly Closing Bal 5", value: "" },
    { label: "Monthly Closing Bal 6", value: "" },
    { label: "Average Bank Balance", value: "100000", isMandatory: true },
    { label: "Average Annual income", value: "100000", isMandatory: true },
    { label: "Opening Balance", value: "10000", isMandatory: true },
    { label: "Statement Period", value: "Rajveer Shikhavat", isMandatory: true },
    { label: "Life Assured Name", value: "Yes", isMandatory: true },
    { label: "Is LA Name Match with Doc Name?", value: "Yes", isMandatory: true },
    { label: "Life Insurance Premium Deduction Entry", value: "" },
    { label: "Wine Beer_Entries", value: "" },
    { label: "Med Entry", value: "" },
  ], 3),
  section("stockHoldingStatement", "Stock Holding Statement", [
    { label: "Is Stock Holding Statement in name of LA/his Business", value: "" },
    { label: "Gross Total Market Value as per the Stmt", value: "10000", isMandatory: true },
    { label: "Income Earned", value: "No" },
    { label: "Derived Income", value: "10000", isMandatory: true },
    { label: "Average Income", value: "10000", isMandatory: true },
  ]),
  section("vehicleOwnershipPapers", "Vehicle Ownership Papers", [
    { label: "Is Registration Papers in the name of LA", value: "" },
    { label: "Is Purchase invoices in the name of LA", value: "" },
    { label: "Purchase Price", value: "10000", isMandatory: true },
    { label: "Vehicle RC Number", value: "" },
    { label: "Derived Income", value: "20000", isMandatory: true },
  ]),
  section("vahan", "Vahan", [
    { label: "Is Registration Papers in the Name of LA", value: "Yes", isMandatory: true },
    { label: "Is Purchase Invoices in the Name of LA", value: "Yes", isMandatory: true },
    { label: "Car RC Number", value: "" },
    { label: "IDV", value: "50000", isMandatory: true },
    { label: "Average Annual Income", value: "100000" },
  ]),
  section("sipStatement", "SIP Statement", [
    { label: "Latest 6 Months SIP Statements Given", value: "Yes", isMandatory: true },
    { label: "Is SIP Statements in the Name of LA", value: "Yes", isMandatory: true },
    { label: "SIP of Month1", value: "January 2025", isMandatory: true },
    { label: "SIP Per Month 1", value: "₹10,000", isMandatory: true },
    { label: "SIP of Month2", value: "February 2025", isMandatory: true },
    { label: "SIP Per Month2", value: "₹10,000", isMandatory: true },
    { label: "SIP of Month 3", value: "March 2025", isMandatory: true },
    { label: "SIP Per Month 3", value: "₹10,000", isMandatory: true },
    { label: "SIP of Month 4", value: "April 2025", isMandatory: true },
    { label: "SIP Per Month4", value: "₹10,000", isMandatory: true },
    { label: "SIP of Month5", value: "May 2025", isMandatory: true },
    { label: "SIP Per Month 5", value: "₹10,000", isMandatory: true },
    { label: "SIP of Month 6", value: "June 2025", isMandatory: true },
    { label: "SIP Per Month 6", value: "₹10,000", isMandatory: true },
    { label: "Average Monthly SIP", value: "₹10,000", isMandatory: true },
    { label: "Average Annual Income", value: "₹12,00,000", isMandatory: true },
  ], 3),
  // section("gstIncome", "GST Income", [
  //   { label: "Assessment Year", value: "at least one year details in GST Income!" },
  //   { label: "Gross Sales", value: "Yes" },
  //   { label: "Gross Purchases", value: "No" },
  //   { label: "Profit After GST", value: "No" },
  //   { label: "Total of Gross Sales", value: "Auto calculate" },
  //   { label: "Average Gross Sales", value: "Auto calculate" },
  //   { label: "Average Annual Income", value: "Auto calculate" },
  // ]),
  section("gstIncome", "GST Income", [
    { label: "Assessment Year", value: "FY 25-26", isMandatory: true },
    { label: "Assessment Year Year 2", value: "", isMandatory: true },
    { label: "Assessment Year Year 3", value: "", isMandatory: true },
    { label: "Assessment Year Year 4", value: "", isMandatory: true },
    { label: "Gross Sales", value: "Yes", isMandatory: true },
    { label: "Gross Sales Year 2", value: "" },
    { label: "Gross Sales Year 3", value: "" },
    { label: "Gross Sales Year 4", value: "" },
    { label: "Gross Purchases", value: "No" },
    { label: "Gross Purchases Year 2", value: "" },
    { label: "Gross Purchases Year 3", value: "" },
    { label: "Gross Purchases Year 4", value: "" },
    { label: "Profit After GST", value: "No" },
    { label: "Profit After GST Year 2", value: "" },
    { label: "Profit After GST Year 3", value: "" },
    { label: "Profit After GST Year 4", value: "" },
    { label: "Total of Gross Sales", value: "100000", isMandatory: true },
    { label: "Total of Gross Sales Year 2", value: "" },
    { label: "Total of Gross Sales Year 3", value: "" },
    { label: "Total of Gross Sales Year 4", value: "" },
    { label: "Average Gross Sales", value: "200000", isMandatory: true },
    { label: "Average Gross Sales Year 2", value: "" },
    { label: "Average Gross Sales Year 3", value: "" },
    { label: "Average Gross Sales Year 4", value: "" },
    { label: "Average Annual Income", value: "300000", isMandatory: true },
    { label: "Average Annual Income Year 2", value: "" },
    { label: "Average Annual Income Year 3", value: "" },
    { label: "Average Annual Income Year 4", value: "" },
  ], 3),
  section("bankStatementSalaryCredit", "Bank Statement with Salary Credit Details", [
    { label: "Is Bank Statement in the Name of LA", value: "Yes", isMandatory: true },
    { label: "Net Salary Month1", value: "January 2025", isMandatory: true },
    { label: "Net Salary Credited PM1", value: "80000", isMandatory: true },
    { label: "Net Salary Month 2", value: "February 2025", isMandatory: true },
    { label: "Net Salary Credited PM2", value: "82000", isMandatory: true },
    { label: "Net Salary Month 3", value: "March 2025", isMandatory: true },
    { label: "Net Salary Credited PM3", value: "81000", isMandatory: true },
    { label: "Net Salary Month 4", value: "" },
    { label: "Net Salary Credited PM4", value: "" },
    { label: "Net Salary Month 5", value: "" },
    { label: "Net Salary Credited PM 5", value: "" },
    { label: "Net Salary Month 6", value: "" },
    { label: "Net Salary Credited PM 6", value: "" },
    { label: "Average Net Salary Credited PM", value: "81000" },
    { label: "Net Salary Credited PA", value: "1069200" },
    { label: "Annual Bonus /Incentive /Reimbursement", value: "0" },
    { label: "Average Annual Income", value: "1069200" },
    { label: "Salary Credited", value: "No" },
    { label: "Opening Balance", value: "150000", isMandatory: true },
    { label: "Closing Balance", value: "No" },
    { label: "Statement Period", value: "January 2025 - March 2025", isMandatory: true },
    { label: "Life Assured Name", value: "Rahul Sharma", isMandatory: true },
    { label: "Is LA Name Match with Doc Name?", value: "Yes", isMandatory: true },
  ], 3),
  section("epfBasic", "EMPLOYEE PROVIDENT FUND - BASIC", [
    { label: "Latest Organization Name", value: "ABC Technologies Pvt. Ltd.", isMandatory: true },
    { label: "Is Organization Name Same?", value: "Yes", isMandatory: true },
    { label: "Income", value: "972000", isMandatory: true },
  ]),
  section("epfAdvanced", "EMPLOYEE PROVIDENT FUND - ADVANCED", [
    { label: "Latest Organization Name", value: "ABC Technologies Pvt. Ltd.", isMandatory: true },
    { label: "Is Organization Name Same?", value: "Yes", isMandatory: true },
    { label: "PF Contribution M1", value: "5000", isMandatory: true },
    { label: "PF Contribution M2", value: "5000", isMandatory: true },
    { label: "PF Contribution M3", value: "5000", isMandatory: true },
    { label: "PF Contribution M4", value: "5000", isMandatory: true },
    { label: "PF Contribution M5", value: "5000", isMandatory: true },
    { label: "PF Contribution M6", value: "5000", isMandatory: true },
    { label: "Annual Income", value: "60000", isMandatory: true },
  ], 3),
];

export const financialSectionOptions = financialSections.map((section) => ({
  key: section.key,
  label: section.title,
}));
