export type FinancialField = {
  label: string;
  value?: string | number | boolean;
  isMandatory?: boolean;
  mandatoryCondition?: string;
};

export type FinancialSectionKey =
  | "appointment_letter"
  | "ca_balance_sheet"
  | "ca_networth"
  | "commission_statement"
  | "computation_of_income"
  | "credit_card"
  | "fixed_deposit_receipt"
  | "form16"
  | "form16a"
  | "form_j"
  | "govt_bonds"
  | "itr_non_individual"
  | "itr_individual"
  | "loan_statement"
  | "mutual_fund"
  | "pension_statement"
  | "profit_and_loss"
  | "property_purchase"
  | "property_valuation"
  | "salary_certificate"
  | "salary_revision_letter"
  | "salary_slips"
  | "bank_statement"
  | "stock_holding"
  | "vehicle_ownership"
  | "vahan"
  | "sip_statement"
  | "gst_income"
  | "bank_statement_salary_credit"
  | "epf_basic"
  | "epf_advanced"
  | "employee_id_card"
  | "advance_tax"
  | "ca_networth"
  | "ca_balance_sheet";

export type FinancialSectionConfig = {
  key: FinancialSectionKey;
  title: string;
  columns?: number;
  items: FinancialField[];
};

const section = (
  key: FinancialSectionKey,
  title: string,
  items: FinancialField[],
  columns = 3,
): FinancialSectionConfig => ({
  key,
  title,
  columns,
  items,
});

export const financialSections: FinancialSectionConfig[] = [
  section("appointment_letter", "Appointment Letter / Contract of Employer", [
    { label: "Name of the company" },
    { label: "Name of the employee" },
    { label: "Joining Date", isMandatory: true },
    { label: "CTC", isMandatory: true },
  ]),
  section("commission_statement", "Commission Statement", [
    { label: "Month 1", isMandatory: true },
    { label: "Month 2"},
    { label: "Month 3"},
    { label: "Month 4"},
    { label: "Month 5"},
    { label: "Month 6"},
    { label: "Average commission pm"},
    { label: "Average Annual Income"},
  ], 4),
  section("computation_of_income", "Computation Of Income", [
    { label: "Assessment Year", isMandatory: true },
    { label: "Assessment Year Year 2", isMandatory: true },
    { label: "Assessment Year Year 3" },
    { label: "Income from Salary(A)", isMandatory: true },
    { label: "Income from Salary(A) Year 2", isMandatory: true },
    { label: "Income from Salary(A) Year 3" },
    { label: "Income from House Property" },
    { label: "Income from House Property Year 2" },
    { label: "Income from House Property Year 3" },
    { label: "Income from Business or Profession (B)", isMandatory: true },
    { label: "Income from Business or Profession (B) Year 2", isMandatory: true },
    { label: "Income from Business or Profession (B) Year 3" },
    { label: "Short term & Capital Gains" },
    { label: "Short term & Capital Gains Year 2" },
    { label: "Short term & Capital Gains Year 3" },
    { label: "Income from Other Sources" },
    { label: "Income from Other Sources Year 2" },
    { label: "Income from Other Sources Year 3" },
    { label: "Agricultural Income" },
    { label: "Agricultural Income Year 2" },
    { label: "Agricultural Income Year 3" },
    { label: "Exempt Income(C)", isMandatory: true },
    { label: "Exempt Income(C) Year 2", isMandatory: true },
    { label: "Exempt Income(C) Year 3" },
    { label: "Gross Total Income"},
    { label: "Gross Total Income Year 2" },
    { label: "Gross Total Income Year 3" },
    { label: "Total Gross Total Income"},
    { label: "Average Gross Total Income"},
  ], 3),
  section("credit_card", "Credit Cards", [
    { label: "Is Credit card statement in the name of LA"},
    { label: "Is LA Defaulter in the Payment"},
    { label: "Type of Card"},
    { label: "Credit Limit", isMandatory: true },
    { label: "Points Earned"},
    { label: "Income Earned"},
    { label: "Derived Income" },
    { label: "Average Income" },
  ]),
  section("fixed_deposit_receipt", "Fixed Deposit Receipt", [
    { label: "Is Fixed Deposit Receipt in the name of LA"},
    { label: "Is Fixed Deposit Receipts matured"},
    { label: "Amount Invested", isMandatory: true },
    { label: "Income Earned"},
    { label: "Derived Income" },
    { label: "Average Income" },
  ]),
  section("form16", "FORM16/FORM 130", [
    { label: "ASSESSMENT", isMandatory: true },
    { label: "ASSESSMENT Year 2" },
    { label: "ASSESSMENT Year 3" },
    { label: "Gross Salary PA", isMandatory: true},
    { label: "Gross Salary PA Year 2"},
    { label: "Gross Salary PA Year 3"},
    { label: "Average Annual Income"},
    { label: "Life Assured Pan No", isMandatory: true},
    { label: "Life Assured Pan No Year 2" },
    { label: "Life Assured Pan No Year 3" },
    { label: "Life Assured Name", isMandatory: true},
    { label: "Life Assured Name Year 2" },
    { label: "Life Assured Name Year 3" },
    { label: "Company Name", isMandatory: true },
    { label: "Company Name Year 2" },
    { label: "Company Name Year 3" },
    { label: "Is Life Assured Name Same With Doc Name?" },
    { label: "Is Life Assured Name Same With Doc Name? Year 2" },
    { label: "Is Life Assured Name Same With Doc Name? Year 3" },
  ], 3),
  section("form16a", "FORM 16A/FORM 131", [
    { label: "Assessment Year", isMandatory: true },
    { label: "Assessment Year Year 2" },
    { label: "Assessment Year Year 3" },
    { label: "Net Receipt pa", isMandatory: true },
    { label: "Net Receipt pa Year 2"},
    { label: "Net Receipt pa Year 3"},
    { label: "Average Annual Income" },
  ], 3),
  section("form_j", "FORM J", [
    { label: "Is Form J in the name of LA", isMandatory: true },
    { label: "Month1 Receipt1", isMandatory: true },
    { label: "Month1 Receipt2"},
    { label: "Month1 Receipt3"},
    { label: "Month1 Receipt4"},
    { label: "Month1 Receipt5"},
    { label: "Month1 Receipt6"},
    { label: "Month2 Receipt1"},
    { label: "Month2 Receipt2"},
    { label: "Month2 Receipt3"},
    { label: "Month2 Receipt4"},
    { label: "Month2 Receipt5"},
    { label: "Month2 Receipt6"},
    { label: "Month3 Receipt1"},
    { label: "Month3 Receipt2"},
    { label: "Month3 Receipt3"},
    { label: "Month3 Receipt4"},
    { label: "Month3 Receipt5"},
    { label: "Month3 Receipt6"},
    { label: "Total Receipts Receipt1" },
    { label: "Average Monthly Receipts Receipt1" },
    { label: "Annual Receipts Receipt1" },
    { label: "Derived Income Receipt1" },
  ], 3),
  section("govt_bonds", "Govt. Of India Bonds", [
    { label: "Is Bond Certification in the name of LA"},
    { label: "Is Bond Certificate matured"},
    { label: "Amount Invested or Maturity Value, whichever higher", isMandatory: true },
    { label: "Income Earned"},
    { label: "Derived Income"},
    { label: "Average Income"},
  ]),
  section("itr_non_individual", "Income Tax Return (Non-Individual)", [
    { label: "Name of Organisation/Firm" },
    { label: "Permanent Account Number" },
    { label: "Assessment Year", isMandatory: true },
    { label: "Assessment Year Year 2", isMandatory: true },
    { label: "Assessment Year Year 3" },
    { label: "ITR Acknowledgement Number" },
    { label: "ITR Acknowledgement Number Year 2" },
    { label: "ITR Acknowledgement Number Year 3" },
    { label: "Income from Salary", isMandatory: true },
    { label: "Income from Salary Year 2", isMandatory: true },
    { label: "Income from Salary Year 3"},
    { label: "Pan Number Matched with Barcode Number"},
    { label: "Pan Number Matched with Barcode Number Year 2"},
    { label: "Pan Number Matched with Barcode Number Year 3"},
    { label: "Income from House Property"},
    { label: "Income from House Property Year 2"},
    { label: "Income from House Property Year 3"},
    { label: "Income from Business or Profession", isMandatory: true },
    { label: "Income from Business or Profession Year 2", isMandatory: true },
    { label: "Income from Business or Profession Year 3"},
    { label: "Short term & Capital Gains"},
    { label: "Short term & Capital Gains Year 2"},
    { label: "Short term & Capital Gains Year 3"},
    { label: "Income from Other Sources"},
    { label: "Income from Other Sources Year 2"},
    { label: "Income from Other Sources Year 3"},
    { label: "Agricultural Income"},
    { label: "Agricultural Income Year 2"},
    { label: "Agricultural Income Year 3"},
    { label: "Exempt Income", isMandatory: true },
    { label: "Exempt Income Year 2", isMandatory: true },
    { label: "Exempt Income Year 3"},
    { label: "Gross Total Income"},
    { label: "Gross Total Income Year 2"},
    { label: "Gross Total Income Year 3"},
    { label: "Total Gross Total Income"},
    { label: "Average Gross Total Income"},
  ], 3),
  section("itr_individual", "Income Tax Return (Individual)", [
    { label: "Name of Organisation/Firm" },
    { label: "Permanent Account Number" },
    { label: "Assessment Year", isMandatory: true },
    { label: "Assessment Year Year 2", isMandatory: true },
    { label: "Assessment Year Year 3" },
    { label: "ITR Acknowledgement Number" },
    { label: "ITR Acknowledgement Number Year 2" },
    { label: "ITR Acknowledgement Number Year 3" },
    { label: "Pan Number Matched with Barcode Number" },
    { label: "Pan Number Matched with Barcode Number Year 2" },
    { label: "Pan Number Matched with Barcode Number Year 3" },
    { label: "Date of Filling ITR", isMandatory: true },
    { label: "Date of Filling ITR Year 2", isMandatory: true},
    { label: "Date of Filling ITR Year 3"},
    { label: "Income from Salary(A)", isMandatory: true },
    { label: "Income from Salary(A) Year 2", isMandatory: true},
    { label: "Income from Salary(A) Year 3"},
    { label: "Income from House Property"},
    { label: "Income from House Property Year 2"},
    { label: "Income from House Property Year 3"},
    { label: "Income from Business or Profession(B)", isMandatory: true },
    { label: "Income from Business or Profession(B) Year 2", isMandatory: true},
    { label: "Income from Business or Profession(B) Year 3"},
    { label: "Short term & Capital Gains"},
    { label: "Short term & Capital Gains Year 2"},
    { label: "Short term & Capital Gains Year 3"},
    { label: "Income from Other Sources"},
    { label: "Income from Other Sources Year 2"},
    { label: "Income from Other Sources Year 3"},
    { label: "Agricultural Income"},
    { label: "Agricultural Income Year 2"},
    { label: "Agricultural Income Year 3"},
    { label: "Exempt Income(C)", isMandatory: true },
    { label: "Exempt Income(C) Year 2", isMandatory: true},
    { label: "Exempt Income(C) Year 3"},
    { label: "Gross Total Income(A+B+C)"},
    { label: "Gross Total Income(A+B+C) Year 2"},
    { label: "Gross Total Income(A+B+C) Year 3"},
    { label: "Total Gross Total Income"},
    { label: "Average Gross Total Income"},
    { label: "PF deduction - Salaried customers"},
    { label: "PF deduction - Salaried customers Year 2"},
    { label: "PF deduction - Salaried customers Year 3"},
    { label: "Life Assured Name", isMandatory: true },
    { label: "Life Assured Name Year 2" },
    { label: "Life Assured Name Year 3" },
    { label: "Is Life Assured Name Same?", isMandatory: true },
    { label: "Is Life Assured Name Same? Year 2", isMandatory: true},
    { label: "Is Life Assured Name Same? Year 3"},
  ], 3),
  section("loan_statement", "Loan Statements", [
    { label: "Is Loan Statements in the name of LA"},
    { label: "Is LA Defaulter in the Payment"},
    { label: "Monthly EMI as per Schedule", isMandatory: true },
    { label: "Income Earned"},
    { label: "Derived Income"},
    { label: "Average Income"},
  ]),
  section("mutual_fund", "Mutual Fund A/C Statement", [
    { label: "Is Mutual Fund Statement in the name of LA"},
    { label: "Latest Market Value (as per NAV) in Statement", isMandatory: true},
    { label: "Income Earned"},
    { label: "Derived Income"},
    { label: "Average Income"},
  ]),
  section("pension_statement", "PENSION STATEMENT", [
    { label: "Total Monthly Pension", isMandatory: true },
    { label: "Pension Received pa"},
  ]),
  section("profit_and_loss", "Profit & Loss A/C", [
    { label: "Name of Organization/Firm", isMandatory: true },
    { label: "Assessment Year", isMandatory: true },
    { label: "Assessment Year Year 2", isMandatory: true },
    { label: "Assessment Year Year 3", isMandatory: true },
    { label: "Shareholders Funds / Partners Capital"},
    { label: "Shareholders Funds / Partners Capital Year 2"},
    { label: "Shareholders Funds / Partners Capital Year 3"},
    { label: "Share Capital or Fixed/Fluctuating Capital"},
    { label: "Share Capital or Fixed/Fluctuating Capital Year 2"},
    { label: "Share Capital or Fixed/Fluctuating Capital Year 3"},
    { label: "Reserves & Surplus"},
    { label: "Reserves & Surplus Year 2"},
    { label: "Reserves & Surplus Year 3"},
    { label: "Total Shareholders Funds or Partner's Fund"},
    { label: "Total Shareholders Funds or Partner's Fund Year 2"},
    { label: "Total Shareholders Funds or Partner's Fund Year 3"},
    { label: "Profit Calculation"},
    { label: "Profit Calculation Year 2"},
    { label: "Profit Calculation Year 3"},
    { label: "Profit Before Depreciation & Tax (PBDT)"},
    { label: "Profit Before Depreciation & Tax (PBDT) Year 2"},
    { label: "Profit Before Depreciation & Tax (PBDT) Year 3"},
    { label: "Less : Depreciation"},
    { label: "Less : Depreciation Year 2"},
    { label: "Less : Depreciation Year 3"},
    { label: "Profit Before Tax (PBT)"},
    { label: "Profit Before Tax (PBT) Year 2"},
    { label: "Profit Before Tax (PBT) Year 3"},
    { label: "Tax"},
    { label: "Tax Year 2"},
    { label: "Tax Year 3"},
    { label: "Profit After Tax (PAT)", isMandatory: true},
    { label: "Profit After Tax (PAT) Year 2", isMandatory: true},
    { label: "Profit After Tax (PAT) Year 3", isMandatory: true},
    { label: "Profit After Tax of Last Year"},
    { label: "Profit After Tax of Last Year Year 2"},
    { label: "Profit After Tax of Last Year Year 3"},
    { label: "Rise In Profit as compared to Last Year"},
    { label: "Rise In Profit as compared to Last Year Year 2"},
    { label: "Rise In Profit as compared to Last Year Year 3"},
    { label: "% Rise In Profit as compared to Last Year"},
    { label: "% Rise In Profit as compared to Last Year Year 2"},
    { label: "% Rise In Profit as compared to Last Year Year 3"},
    { label: "Income Calculation"},
    { label: "Income Calculation Year 2"},
    { label: "Income Calculation Year 3"},
    { label: "Sales"},
    { label: "Sales Year 2"},
    { label: "Sales Year 3"},
    { label: "Sales of Last Year"},
    { label: "Sales of Last Year Year 2"},
    { label: "Sales of Last Year Year 3"},
    { label: "Rise In Sales as compared to Last Year"},
    { label: "Rise In Sales as compared to Last Year Year 2"},
    { label: "Rise In Sales as compared to Last Year Year 3"},
    { label: "% Rise In Sales as compared to Last Year"},
    { label: "% Rise In Sales as compared to Last Year Year 2"},
    { label: "% Rise In Sales as compared to Last Year Year 3"},
    { label: "Average Gross Income" },
    { label: "Average Profit Before Tax"},
    { label: "Average Profit After Tax"},
  ], 3),
  section("property_purchase", "Property Purchase Documents", [
    { label: "Is Property purchased by LA"},
    { label: "Purchase Price", isMandatory: true },
    { label: "Financial Year of Purchase"},
    { label: "Estimated Market Value of Property"},
    { label: "Derived Income"},
  ]),
  section("property_valuation", "Property Valuation Report", [
    { label: "Is Property Valuation Report in the name of LA"},
    { label: "Estimated Market Value of Property(as per report)", isMandatory: true },
    { label: "Derived Income"},
  ]),
  section("salary_certificate", "Salary Certificate", [
    { label: "Gross Salary PA", isMandatory: true },
    { label: "Derived Income" },
  ]),
  section("salary_revision_letter", "Salary Revision Letter", [
    { label: "Gross Salary PA", isMandatory: true },
    { label: "Derived Income" },
  ]),
  section("salary_slips", "SALARY SLIPS", [
    { label: "Gross Salary Pm1", isMandatory: true },
    { label: "Gross Salary Pm2", isMandatory: true },
    { label: "Gross Salary Pm3", isMandatory: true },
    { label: "Gross Salary Pm4"},
    { label: "Gross Salary Pm5"},
    { label: "Gross Salary Pm6"},
    { label: "Average Salary pm"},
    { label: "Gross Salary pa"},
    { label: "Annual Bonus/Incentive/Reimbursement"},
    { label: "Average Annual Income"},
    { label: "Company Name", isMandatory: true },
    { label: "Life Assured Name", isMandatory: true },
    { label: "Is Life Assured Name Same?", isMandatory: true },
    { label: "PF / UAN No"},
  ], 3),
  section("bank_statement", "Savings A/C & Current A/C Bank Statements", [
    { label: "Is Bank Statement in the name of LA/his Business", isMandatory: true },
    { label: "Latest 6 months statements given", isMandatory: true },
    { label: "Any Overdraft(Negative/Debit) Balances", isMandatory: true },
    { label: "Monthly Closing Bal 1", isMandatory: true },
    { label: "Monthly Closing Bal 2", isMandatory: true},
    { label: "Monthly Closing Bal 3", isMandatory: true},
    { label: "Monthly Closing Bal 4", isMandatory: true},
    { label: "Monthly Closing Bal 5", isMandatory: true},
    { label: "Monthly Closing Bal 6", isMandatory: true},
    { label: "Average Bank Balance" },
    { label: "Average Annual income" },
    { label: "Opening Balance", isMandatory: true },
    { label: "Statement Period", isMandatory: true },
    { label: "Life Assured Name", isMandatory: true },
    { label: "Is LA Name Match with Doc Name?", isMandatory: true },
    { label: "Life Insurance Premium Deduction Entry"},
    { label: "Wine Beer_Entries"},
    { label: "Med Entry"},
  ], 3),
  section("stock_holding", "Stock Holding Statement", [
    { label: "Is Stock Holding Stmt in name of LA/his Business"},
    { label: "Gross Total Market Value as per the Stmt", isMandatory: true },
    { label: "Income Earned"},
    { label: "Derived Income"},
    { label: "Average Income"},
  ]),
  section("vehicle_ownership", "Vehicle Ownership Papers", [
    { label: "Is Registration Papers in the name of LA"},
    { label: "Is Purchase invoices in the name of LA"},
    { label: "Purchase Price", isMandatory: true },
    { label: "Vehicle RC Number"},
    { label: "Derived Income" },
  ]),
  section("vahan", "Vahan", [
    { label: "Is Registration Papers in the Name of LA", isMandatory: true },
    { label: "Is Purchase Invoices in the Name of LA", isMandatory: true },
    { label: "Car RC Number"},
    { label: "IDV", isMandatory: true },
    { label: "Average Annual Income"},
  ]),
  section("sip_statement", "SIP Statement", [
    { label: "Latest 6 Months SIP Statements Given", isMandatory: true },
    { label: "Is SIP Statements in the Name of LA", isMandatory: true },
    { label: "SIP of Month1", isMandatory: true },
    { label: "SIP Per Month 1", isMandatory: true },
    { label: "SIP of Month2", isMandatory: true },
    { label: "SIP Per Month2", isMandatory: true },
    { label: "SIP of Month 3", isMandatory: true },
    { label: "SIP Per Month 3", isMandatory: true },
    { label: "SIP of Month 4", isMandatory: true },
    { label: "SIP Per Month4", isMandatory: true },
    { label: "SIP of Month5", isMandatory: true },
    { label: "SIP Per Month 5", isMandatory: true },
    { label: "SIP of Month 6", isMandatory: true },
    { label: "SIP Per Month 6", isMandatory: true },
    { label: "Average Monthly SIP" },
    { label: "Average Annual Income" },
  ], 3),
  section("gst_income", "GST Income", [
    { label: "Assessment Year", isMandatory: true },
    { label: "Assessment Year Year 2" },
    { label: "Assessment Year Year 3" },
    { label: "Assessment Year Year 4" },
    { label: "Gross Sales", isMandatory: true },
    { label: "Gross Sales Year 2"},
    { label: "Gross Sales Year 3"},
    { label: "Gross Sales Year 4"},
    { label: "Gross Purchases"},
    { label: "Gross Purchases Year 2"},
    { label: "Gross Purchases Year 3"},
    { label: "Gross Purchases Year 4"},
    { label: "Profit After GST"},
    { label: "Profit After GST Year 2"},
    { label: "Profit After GST Year 3"},
    { label: "Profit After GST Year 4"},
    { label: "Total of Gross Sales" },
    { label: "Average Gross Sales" },
    { label: "Average Annual Income" },
  ], 3),
  section("bank_statement_salary_credit", "Bank Statement with Salary Credit Details", [
    { label: "Is Bank Statement in the Name of LA", isMandatory: true },
    { label: "Net Salary Month1", isMandatory: true },
    { label: "Net Salary Credited PM1", isMandatory: true },
    { label: "Net Salary Month 2", isMandatory: true },
    { label: "Net Salary Credited PM2", isMandatory: true },
    { label: "Net Salary Month 3", isMandatory: true },
    { label: "Net Salary Credited PM3", isMandatory: true },
    { label: "Net Salary Month 4"},
    { label: "Net Salary Credited PM4"},
    { label: "Net Salary Month 5"},
    { label: "Net Salary Credited PM 5"},
    { label: "Net Salary Month 6"},
    { label: "Net Salary Credited PM 6"},
    { label: "Average Net Salary Credited PM"},
    { label: "Net Salary Credited PA"},
    { label: "Annual Bonus /Incentive /Reimbursement"},
    { label: "Average Annual Income"},
    { label: "Salary Credited"},
    { label: "Opening Balance", isMandatory: true },
    { label: "Closing Balance"},
    { label: "Statement Period", isMandatory: true },
    { label: "Life Assured Name", isMandatory: true },
    { label: "Is LA Name Match with Doc Name?", isMandatory: true },
  ], 3),
  section("epf_basic", "EMPLOYEE PROVIDENT FUND - BASIC", [
    { label: "Latest Organization Name", isMandatory: true },
    { label: "Is Organization Name Same?", isMandatory: true },
    { label: "Income", isMandatory: true },
  ]),
  section("epf_advanced", "EMPLOYEE PROVIDENT FUND - ADVANCED", [
    { label: "Latest Organization Name", isMandatory: true },
    { label: "Is Organization Name Same?", isMandatory: true },
    { label: "PF Contribution M1", isMandatory: true },
    { label: "PF Contribution M2", isMandatory: true },
    { label: "PF Contribution M3", isMandatory: true },
    { label: "PF Contribution M4", isMandatory: true },
    { label: "PF Contribution M5", isMandatory: true },
    { label: "PF Contribution M6", isMandatory: true },
    { label: "Annual Income" },
  ], 3),
  section("employee_id_card", "Employee ID Card", [
    { label: "Name of the company", isMandatory: true },
    { label: "Name of the employee", isMandatory: true },
    { label: "Employee number", isMandatory: true },
    { label: "Photo available", isMandatory: true },
  ], 3),
];

export const financialSectionOptions = financialSections.map((section) => ({
  key: section.key,
  label: section.title,
}));
