import type { ApplicantInfoTab, ApplicantTab } from "../types/drs.types";

export const reasonOptions = [
  { value: "tea", label: "Tea / Coffee Break" },
  { value: "lunch", label: "Lunch Break" },
  { value: "personal", label: "Personal Work" },
  { value: "meeting", label: "Internal Meeting" },
  { value: "system", label: "System Issue" },
];
export const breakDurationOptions = [
  { label: "15 minutes", value: "15" },
  { label: "30 minutes", value: "30" },
  { label: "45 minutes", value: "45" },
  { label: "60 minutes", value: "60" },
  { label: "90 minutes", value: "90" },
  { label: "120 minutes", value: "120" },
];

export const caseUWDecisionOptions = [
  { label: "Accept", value: "Accept" },
  { label: "Reject", value: "Reject" },
  { label: "Decline", value: "Decline" },
  { label: "Postpone", value: "Postpone" },
  { label: "Counter Offer", value: "Counter Offer" },
  { label: "Refer to HoD", value: "Refer to HoD" },
  { label: "Refer to Sr.UW", value: "Refer to Sr.UW" },
  { label: "Refer to Reinsurer", value: "Refer to Reinsurer" },
  { label: "Refer to HO CMO", value: "Refer to HO CMO" },
  { label: "Refer to Risk", value: "Refer to Risk" },
  { label: "Refer to Accuity", value: "Refer to Accuity" },
  { label: "Raise Requirement", value: "Raise Requirement" },
  { label: "Refer to CUW Claim Pool", value: "Refer to CUW Claim Pool" },
  { label: "Hold", value: "Hold" },
];

export const firstUWDecisionOptions = [
  { label: "Accept", value: "Accept" },
  { label: "Counter Offer", value: "Counter Offer" },
  { label: "Reject", value: "Reject" },
  { label: "Decline", value: "Decline" },
  { label: "Postpone", value: "Postpone" },
  {
    label: "Raise Requirement",
    value: "Raise Requirement",
  },
];

export const decisionCodeOptions = [
  {label: "XXR", value: "XXR"},
  {label: "TAX", value: "TAX"},
  {label: "TJX", value: "TJX"},
];

export const parallelUWDecisionOptions = [
  { label: "Raise Requirement", value: "Raise Requirement" },
  { label: "Refer to HO CMO", value: "Refer to HO CMO" },
  { label: "Refer to Risk", value: "Refer to Risk" },
  { label: "Refer to Accuity", value: "Refer to Accuity" },
  { label: "Tele MER/ Video MER", value: "Tele MER/ Video MER" },  
  { label: "None", value: "None" },
];

export const ReferralRisk = [
  { label: "Adverse Profile", value: "Adverse Profile" },
  { label: "DRC Adverse", value: "DRC Adverse" },
  { label: "IIB Adverse", value: "IIB Adverse" },
  { label: "PTRL Adverse", value: "PTRL Adverse" },
];

export const AccuityReferralReasons = [
  { label: "Reason 1", value: "Reason 1" },
  { label: "Reason 2", value: "Reason 2" },
  { label: "Reason 3", value: "Reason 3" },
];

export const ReinsurerReferralReasons = [
  { label: "Reason 1", value: "Reason 1" },
  { label: "Reason 2", value: "Reason 2" },
  { label: "Reason 3", value: "Reason 3" },
];

export const HoldReasons = [
  { label: "Reason 1", value: "Reason 1" },
  { label: "Reason 2", value: "Reason 2" },
  { label: "Reason 3", value: "Reason 3" },
];

export const CUWReferralReasons = [
  { label: "Reason 1", value: "Reason 1" },
  { label: "Reason 2", value: "Reason 2" },
  { label: "Reason 3", value: "Reason 3" },
];

export const ReinsurerOptions = [
  { label: "Swiss Re", value: "Swiss Re" },
  { label: "Munich Re", value: "Munich Re" },
  { label: "SCOR Re", value: "SCOR Re" },
  { label: "Hannover Re", value: "Hannover Re" },
  { label: "RGA", value: "RGA" },
  { label: "GenRe", value: "GenRe" },
];

export const cvtDecisionOptions = [
  { label: "Accept", value: "Accept" },
  { label: "Raise Requirements", value: "Raise Requirements" },
  { label: "Refer to Risk", value: "Refer to Risk" },
  // { label: "Refer to IT", value: "Refer to IT" },
  { label: "Reraise PIVV", value: "Reraise PIVV" },
  { label: "Refer to CUW", value: "Refer to CUW" },
];
export const dvtDecisionOptions = [
  { label: "Raise Requirements", value: "Raise Requirements" },
  { label: "Refer to IT", value: "Refer to IT" },
  { label: "Hold", value: "Hold" },
];

export const applicantTabs: { key: ApplicantTab; label: string }[] = [
  { key: "proposer", label: "Proposer" },
  { key: "lifeassured1", label: "Life Assured 1" },
  { key: "lifeassured2", label: "Life Assured 2" },
];

export const applicantInfoTabs: { key: ApplicantInfoTab; label: string }[] = [
  { key: "imageDetails", label: "Image Details" },
  { key: "personalKyc", label: "Personal & KYC" },
  { key: "contactAddress", label: "Contact & Address" },
  { key: "financialProfession", label: "Financial & Profession" },
  { key: "medicalLifestyle", label: "Medical & Lifestyle" },
  { key: "nominee", label: "Nominee" },
  { key: "generic", label: "Generic" },
  { key: "eia", label: "eIA" },
  { key: "fundDetails", label: "Fund Details" },
  { key: "paymentPayoutDetails", label: "Payment & Payout" },
];

export const GenderOptions = [
  { label: "Male", value: "Male" },
  { label: "Female", value: "Female" },
  { label: "Transgender", value: "Transgender" },
];

export const NationalityOptions = [
  { label: "Indian", value: "Indian" },
  { label: "Non-Indian", value: "Non-Indian" },
  { label: "Not Answered", value: "Not Answered" },
];

export const IDProofOptions = [
  {label: "PAN Card", value: "PAN Card"},
  {label: "Voter ID", value: "Voter ID"},
  {label: "Aadhaar Card", value: "Aadhaar Card"},
  {label: "Passport", value: "Passport"},
  {label: "Driving's License", value: "Driving's License"},
];

export const AddressProofOptions = [
  {label: "PAN Card", value: "PAN Card"},
  {label: "Voter ID", value: "Voter ID"},
  {label: "Aadhaar Card", value: "Aadhaar Card"},
  {label: "Passport", value: "Passport"},
  {label: "Driving's License", value: "Driving's License"},
];

export const StateOptions = [
  { label: "Andaman & Nicobar (UT)", value: "Andaman & Nicobar (UT)" },
  { label: "Andhra Pradesh", value: "Andhra Pradesh" },
  { label: "Assam", value: "Assam" },
  { label: "Bihar", value: "Bihar" },
  { label: "Chandigarh (UT)", value: "Chandigarh (UT)" },
  { label: "Chhattisgarh", value: "Chhattisgarh" },
  {
    label: "Dadra and Nagar Haveli (UT)",
    value: "Dadra and Nagar Haveli (UT)",
  },
  { label: "Daman and Diu (UT)", value: "Daman and Diu (UT)" },
  { label: "Delhi (UT)", value: "Delhi (UT)" },
  { label: "Goa", value: "Goa" },
  { label: "Gujarat", value: "Gujarat" },
  { label: "Haryana", value: "Haryana" },
  { label: "Himachal Pradesh", value: "Himachal Pradesh" },
  { label: "Jammu & Kashmir", value: "Jammu & Kashmir" },
  { label: "Jharkhand", value: "Jharkhand" },
  { label: "Karnataka", value: "Karnataka" },
  { label: "Kerala", value: "Kerala" },
  { label: "Lakshadweep (UT)", value: "Lakshadweep (UT)" },
  { label: "Madhya Pradesh", value: "Madhya Pradesh" },
  { label: "Maharashtra", value: "Maharashtra" },
  { label: "Manipur", value: "Manipur" },
  { label: "Meghalaya", value: "Meghalaya" },
  { label: "Mizoram", value: "Mizoram" },
  { label: "Nagaland", value: "Nagaland" },
  { label: "Odisha", value: "Odisha" },
  { label: "Others", value: "Others" },
  { label: "Puducherry (UT)", value: "Puducherry (UT)" },
  { label: "Punjab", value: "Punjab" },
  { label: "Rajasthan", value: "Rajasthan" },
  { label: "Sikkim", value: "Sikkim" },
  { label: "Tamil Nadu", value: "Tamil Nadu" },
  { label: "Telangana", value: "Telangana" },
  { label: "Tripura", value: "Tripura" },
  { label: "Uttar Pradesh", value: "Uttar Pradesh" },
  { label: "Uttarakhand", value: "Uttarakhand" },
  { label: "West Bengal", value: "West Bengal" },
];

export const CountryOptions = [
  { label: "Abkhazia", value: "Abkhazia" },
  { label: "Afghanistan", value: "Afghanistan" },
  { label: "Aland", value: "Aland" },
  { label: "Albania", value: "Albania" },
  { label: "Algeria", value: "Algeria" },
  { label: "American Samoa", value: "American Samoa" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Anguilla", value: "Anguilla" },
  { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armenia", value: "Armenia" },
  { label: "Aruba", value: "Aruba" },
  { label: "Ascension", value: "Ascension" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Azerbaijan", value: "Azerbaijan" },
  { label: "Bahamas", value: "Bahamas" },
  { label: "Bahrain", value: "Bahrain" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Barbados", value: "Barbados" },
  { label: "Belarus", value: "Belarus" },
  { label: "Belgium", value: "Belgium" },
  { label: "Belize", value: "Belize" },
  { label: "Benin", value: "Benin" },
  { label: "Bermuda", value: "Bermuda" },
  { label: "Bhutan", value: "Bhutan" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { label: "Botswana", value: "Botswana" },
  { label: "Brazil", value: "Brazil" },
  { label: "Brunei Darussalam", value: "Brunei Darussalam" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Cambodia", value: "Cambodia" },
  { label: "Cameroon", value: "Cameroon" },
  { label: "Canada", value: "Canada" },
  { label: "Cape Verde", value: "Cape Verde" },
  { label: "Cayman Islands", value: "Cayman Islands" },
  { label: "Central African Republic", value: "Central African Republic" },
  { label: "Chad", value: "Chad" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Colombia", value: "Colombia" },
  { label: "Comoros", value: "Comoros" },
  { label: "Congo (Brazzaville)", value: "Congo (Brazzaville)" },
  { label: "Congo (Kinshasa)", value: "Congo (Kinshasa)" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Croatia", value: "Croatia" },
  { label: "Cuba", value: "Cuba" },
  { label: "Curacao", value: "Curacao" },
  { label: "Cyprus", value: "Cyprus" },
  { label: "Czech Republic", value: "Czech Republic" },
  { label: "Denmark", value: "Denmark" },
  { label: "Djibouti", value: "Djibouti" },
  { label: "Dominica", value: "Dominica" },
  { label: "Dominican Republic", value: "Dominican Republic" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Egypt", value: "Egypt" },
  { label: "El Salvador", value: "El Salvador" },
  { label: "Equatorial Guinea", value: "Equatorial Guinea" },
  { label: "Eritrea", value: "Eritrea" },
  { label: "Estonia", value: "Estonia" },
  { label: "Ethiopia", value: "Ethiopia" },
  { label: "Faroe Islands", value: "Faroe Islands" },
  { label: "Fiji", value: "Fiji" },
  { label: "Finland", value: "Finland" },
  { label: "France", value: "France" },
  { label: "French Guiana", value: "French Guiana" },
  { label: "French Polynesia", value: "French Polynesia" },
  { label: "Gabon", value: "Gabon" },
  { label: "Gambia", value: "Gambia" },
  { label: "Georgia", value: "Georgia" },
  { label: "Germany", value: "Germany" },
  { label: "Ghana", value: "Ghana" },
  { label: "Gibraltar", value: "Gibraltar" },
  { label: "Greece", value: "Greece" },
  { label: "Greenland", value: "Greenland" },
  { label: "Grenada", value: "Grenada" },
  { label: "Guadeloupe", value: "Guadeloupe" },
  { label: "Guam", value: "Guam" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Guinea", value: "Guinea" },
  { label: "Guinea-Bissau", value: "Guinea-Bissau" },
  { label: "Guyana", value: "Guyana" },
  { label: "Haiti", value: "Haiti" },
  { label: "Honduras", value: "Honduras" },
  { label: "Hong Kong", value: "Hong Kong" },
  { label: "Hungary", value: "Hungary" },
  { label: "Iceland", value: "Iceland" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Iran", value: "Iran" },
  { label: "Iraq", value: "Iraq" },
  { label: "Ireland", value: "Ireland" },
  { label: "Israel", value: "Israel" },
  { label: "Italy", value: "Italy" },
  { label: "Ivory Coast", value: "Ivory Coast" },
  { label: "Jamaica", value: "Jamaica" },
  { label: "Japan", value: "Japan" },
  { label: "Jordan", value: "Jordan" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Kenya", value: "Kenya" },
  { label: "Kuwait", value: "Kuwait" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan" },
  { label: "Laos", value: "Laos" },
  { label: "Latvia", value: "Latvia" },
  { label: "Lebanon", value: "Lebanon" },
  { label: "Lesotho", value: "Lesotho" },
  { label: "Liberia", value: "Liberia" },
  { label: "Libya", value: "Libya" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Lithuania", value: "Lithuania" },
  { label: "Luxembourg", value: "Luxembourg" },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Malawi", value: "Malawi" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Maldives", value: "Maldives" },
  { label: "Mali", value: "Mali" },
  { label: "Malta", value: "Malta" },
  { label: "Mauritania", value: "Mauritania" },
  { label: "Mauritius", value: "Mauritius" },
  { label: "Mexico", value: "Mexico" },
  { label: "Moldova", value: "Moldova" },
  { label: "Monaco", value: "Monaco" },
  { label: "Mongolia", value: "Mongolia" },
  { label: "Montenegro", value: "Montenegro" },
  { label: "Morocco", value: "Morocco" },
  { label: "Mozambique", value: "Mozambique" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Namibia", value: "Namibia" },
  { label: "Nepal", value: "Nepal" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Nicaragua", value: "Nicaragua" },
  { label: "Niger", value: "Niger" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "North Korea", value: "North Korea" },
  { label: "Norway", value: "Norway" },
  { label: "Oman", value: "Oman" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Panama", value: "Panama" },
  { label: "Papua New Guinea", value: "Papua New Guinea" },
  { label: "Paraguay", value: "Paraguay" },
  { label: "Peru", value: "Peru" },
  { label: "Philippines", value: "Philippines" },
  { label: "Poland", value: "Poland" },
  { label: "Portugal", value: "Portugal" },
  { label: "Qatar", value: "Qatar" },
  { label: "Romania", value: "Romania" },
  { label: "Russia", value: "Russia" },
  { label: "Rwanda", value: "Rwanda" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Senegal", value: "Senegal" },
  { label: "Serbia", value: "Serbia" },
  { label: "Singapore", value: "Singapore" },
  { label: "Slovakia", value: "Slovakia" },
  { label: "Slovenia", value: "Slovenia" },
  { label: "Somalia", value: "Somalia" },
  { label: "South Africa", value: "South Africa" },
  { label: "South Korea", value: "South Korea" },
  { label: "Spain", value: "Spain" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Sudan", value: "Sudan" },
  { label: "Sweden", value: "Sweden" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Syria", value: "Syria" },
  { label: "Taiwan", value: "Taiwan" },
  { label: "Tanzania", value: "Tanzania" },
  { label: "Thailand", value: "Thailand" },
  { label: "Togo", value: "Togo" },
  { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { label: "Tunisia", value: "Tunisia" },
  { label: "Turkey", value: "Turkey" },
  { label: "Uganda", value: "Uganda" },
  { label: "Ukraine", value: "Ukraine" },
  { label: "United Arab Emirates", value: "United Arab Emirates" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "United States", value: "United States" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Uzbekistan", value: "Uzbekistan" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Vatican City", value: "Vatican City" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Yemen", value: "Yemen" },
  { label: "Zambia", value: "Zambia" },
  { label: "Zimbabwe", value: "Zimbabwe" },
];

export const applicationDetailsFields = [
  { label: "DoB", key: "dob" },
  { label: "Name of Proposer", key: "nameOfProposer" },
  { label: "Product Opted", key: "productOpted" },
  { label: "Plan Opted", key: "planOpted" },
  { label: "Applied SA", key: "appliedSA" },
  { label: "Premium", key: "premium" },
  { label: "Client Type", key: "clientType" },
  { label: "Last Bucket", key: "lastBucket" },
  { label: "Last User", key: "lastUser" },
] as const;
